package workflows

import (
	"context"
	"errors"
	"strings"

	"opensight/internal/llm"
)

// ProposeProfileInput is the proposal request: the user-entered
// name/website plus the FetchSite text (primary evidence, "" on fetch failure)
// and the web_search location hint. The model does its own web research; there
// is no separate research summary. Customer questions are generated by a
// separate on-demand call after the user reviews Services, so this input
// carries no prompt limit.
type ProposeProfileInput struct {
	Name     string
	Website  string
	SiteText string
	Location llm.Location
}

// ProposeProfileOutput carries the decoded proposal payload (Sources already
// populated) for GenerateProfileWorker to persist. Proposed is false when
// validation still failed after llm.MaxProposeProfileAttempts — no
// profile_proposals row may be written in that case; treat it like a hard
// generation failure. OpenedOwnSite is true when the model's
// web-search actions include an open_page on the business website's own domain,
// i.e. it read the site itself — the job uses this to decide whether to
// override low_confidence when FetchSite failed.
type ProposeProfileOutput struct {
	Payload        llm.ProposalPayload
	Model          string
	Proposed       bool
	OpenedOwnSite  bool
	ValidationErrs []string
}

// ProposeProfile runs the single structured-output proposal call with
// deterministic validation and one validation-retry (design 03 step 3).
//
// Empty name is bad input and non-retryable. A runner error the runner marks
// non-retryable (400-class, content-policy refusal) won't fix on retry, so it
// becomes non-retryable too; every other error propagates for River's
// default retry. A proposal that still fails validation after the retry
// returns Proposed=false (not an error) so the calling job's failure
// posture decides what to do.
func (a *Operations) ProposeProfile(ctx context.Context, in ProposeProfileInput) (ProposeProfileOutput, error) {
	name := strings.TrimSpace(in.Name)
	if name == "" {
		return ProposeProfileOutput{}, NewPermanentError(
			"propose profile", "BadInput", errors.New("business name is required"))
	}

	if err := a.Limiter.Acquire(ctx); err != nil {
		return ProposeProfileOutput{}, err
	}
	result, err := llm.ProposeWithRetry(ctx, a.Proposer, llm.ProposeProfileInput{
		Name:     name,
		Website:  in.Website,
		SiteText: in.SiteText,
		Location: in.Location,
	})
	a.Limiter.Release()
	if err != nil {
		if errors.Is(err, llm.ErrNonRetryable) {
			return ProposeProfileOutput{}, NewPermanentError(
				"propose profile", "ProposalRefused", err)
		}
		return ProposeProfileOutput{}, err
	}

	if !result.Proposed {
		// Never log SiteText or the raw model JSON (PII/scraped content) — only the
		// business name and the deterministic failures.
		actLogger(ctx).Warn("propose profile: proposal failed validation after retry",
			"business_name", name, "validation_errors", result.ValidationErrs)
		return ProposeProfileOutput{
			Model:          result.Model,
			Proposed:       false,
			ValidationErrs: result.ValidationErrs,
		}, nil
	}

	// Sources are the pages the model opened while researching; OpenedOwnSite
	// records whether it read the business's own site (both derived from the raw
	// response's web-search actions — neither is asked of the model).
	actions := llm.ParseWebSearchActions(result.RawResponse)
	payload := result.Payload
	payload.Sources = llm.SourcesFromWebSearch(result.RawResponse)
	openedOwnSite := llm.OpenedSiteDomain(actions, in.Website)

	// Observability for "did this actually search, or did it guess/run in
	// stub mode": model is a real OpenAI model id when a live call ran and the
	// fixed "stub-propose-profile" marker in stub/replay mode; action_counts
	// being empty on a live model means tool_choice:"required" did not force a
	// search, which should not happen but is worth being able to see. Never
	// log SiteText or the raw model JSON here (PII/scraped content).
	actionCounts := map[string]int{}
	for _, a := range actions {
		actionCounts[a.Type]++
	}
	actLogger(ctx).Info("propose profile: generated",
		"business_name", name,
		"model", result.Model,
		"category", payload.Profile.Category,
		"low_confidence", payload.LowConfidence,
		"web_search_action_counts", actionCounts,
		"opened_own_site", openedOwnSite,
		"source_count", len(payload.Sources))

	return ProposeProfileOutput{
		Payload:       payload,
		Model:         result.Model,
		Proposed:      true,
		OpenedOwnSite: openedOwnSite,
	}, nil
}
