// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const appendSuggestedAlias = `-- name: AppendSuggestedAlias :exec
UPDATE competitors SET suggested_aliases=array_append(suggested_aliases,$3)
WHERE id=$1 AND business_id=$2 AND NOT ($3=ANY(suggested_aliases)) AND NOT ($3=ANY(aliases))
`

type AppendSuggestedAliasParams struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	ArrayAppend interface{}
}

func (q *Queries) AppendSuggestedAlias(ctx context.Context, arg AppendSuggestedAliasParams) error {
	_, err := q.db.Exec(ctx, appendSuggestedAlias, arg.ID, arg.BusinessID, arg.ArrayAppend)
	return err
}

const deleteCitationsByResult = `-- name: DeleteCitationsByResult :exec
DELETE FROM citations WHERE prompt_result_id=$1
`

func (q *Queries) DeleteCitationsByResult(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCitationsByResult, promptResultID)
	return err
}

const deleteResultAnalysis = `-- name: DeleteResultAnalysis :exec
DELETE FROM result_analyses WHERE prompt_result_id=$1 AND prompt_result_id IN (
 SELECT pr.id FROM prompt_results pr JOIN monitoring_runs r ON r.id=pr.run_id
 JOIN businesses b ON b.id=r.business_id WHERE b.account_id = $2)
`

type DeleteResultAnalysisParams struct {
	PromptResultID uuid.UUID
	AccountID      uuid.UUID
}

func (q *Queries) DeleteResultAnalysis(ctx context.Context, arg DeleteResultAnalysisParams) error {
	_, err := q.db.Exec(ctx, deleteResultAnalysis, arg.PromptResultID, arg.AccountID)
	return err
}

const deleteResultCitations = `-- name: DeleteResultCitations :exec
DELETE FROM citations WHERE prompt_result_id=$1 AND prompt_result_id IN (
 SELECT pr.id FROM prompt_results pr JOIN monitoring_runs r ON r.id=pr.run_id
 JOIN businesses b ON b.id=r.business_id WHERE b.account_id = $2)
`

type DeleteResultCitationsParams struct {
	PromptResultID uuid.UUID
	AccountID      uuid.UUID
}

func (q *Queries) DeleteResultCitations(ctx context.Context, arg DeleteResultCitationsParams) error {
	_, err := q.db.Exec(ctx, deleteResultCitations, arg.PromptResultID, arg.AccountID)
	return err
}

const deleteRunMentions = `-- name: DeleteRunMentions :exec
DELETE FROM mentions WHERE prompt_result_id IN (
 SELECT pr.id FROM prompt_results pr JOIN monitoring_runs r ON r.id=pr.run_id
 JOIN businesses b ON b.id=r.business_id WHERE r.id = $1 AND b.account_id = $2)
`

type DeleteRunMentionsParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteRunMentions(ctx context.Context, arg DeleteRunMentionsParams) error {
	_, err := q.db.Exec(ctx, deleteRunMentions, arg.ID, arg.AccountID)
	return err
}

const insertCitation = `-- name: InsertCitation :exec
INSERT INTO citations (id,prompt_result_id,url,domain,title,cite_order,subject,text_start,text_end)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertCitationParams struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Url            string
	Domain         string
	Title          *string
	CiteOrder      int32
	Subject        string
	TextStart      int32
	TextEnd        int32
}

func (q *Queries) InsertCitation(ctx context.Context, arg InsertCitationParams) error {
	_, err := q.db.Exec(ctx, insertCitation,
		arg.ID,
		arg.PromptResultID,
		arg.Url,
		arg.Domain,
		arg.Title,
		arg.CiteOrder,
		arg.Subject,
		arg.TextStart,
		arg.TextEnd,
	)
	return err
}

const insertDiscoveredCompetitor = `-- name: InsertDiscoveredCompetitor :exec
INSERT INTO competitors (id,business_id,name,aliases,source,status)
VALUES ($1,$2,$3,ARRAY[$3]::text[],'discovered','discovered')
`

type InsertDiscoveredCompetitorParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	Name       string
}

func (q *Queries) InsertDiscoveredCompetitor(ctx context.Context, arg InsertDiscoveredCompetitorParams) error {
	_, err := q.db.Exec(ctx, insertDiscoveredCompetitor, arg.ID, arg.BusinessID, arg.Name)
	return err
}

const insertMention = `-- name: InsertMention :exec
INSERT INTO mentions (id,prompt_result_id,subject,competitor_id,matched_by,mention_order,verbatim_name,excerpt)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertMentionParams struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Subject        string
	CompetitorID   *uuid.UUID
	MatchedBy      string
	MentionOrder   int32
	VerbatimName   *string
	Excerpt        string
}

func (q *Queries) InsertMention(ctx context.Context, arg InsertMentionParams) error {
	_, err := q.db.Exec(ctx, insertMention,
		arg.ID,
		arg.PromptResultID,
		arg.Subject,
		arg.CompetitorID,
		arg.MatchedBy,
		arg.MentionOrder,
		arg.VerbatimName,
		arg.Excerpt,
	)
	return err
}

const insertMentionCitation = `-- name: InsertMentionCitation :execrows
INSERT INTO mention_citations (mention_id,citation_id)
SELECT $1,c.id FROM citations c
WHERE c.prompt_result_id=$2 AND c.cite_order=$3
`

type InsertMentionCitationParams struct {
	MentionID      uuid.UUID
	PromptResultID uuid.UUID
	CiteOrder      int32
}

func (q *Queries) InsertMentionCitation(ctx context.Context, arg InsertMentionCitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMentionCitation, arg.MentionID, arg.PromptResultID, arg.CiteOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAnalysisCompetitors = `-- name: ListAnalysisCompetitors :many
SELECT id,name,website,aliases,status FROM competitors
WHERE business_id = $1 AND business_id IN (SELECT id FROM businesses WHERE account_id = $2)
ORDER BY created_at
`

type ListAnalysisCompetitorsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type ListAnalysisCompetitorsRow struct {
	ID      uuid.UUID
	Name    string
	Website *string
	Aliases []string
	Status  string
}

func (q *Queries) ListAnalysisCompetitors(ctx context.Context, arg ListAnalysisCompetitorsParams) ([]ListAnalysisCompetitorsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisCompetitors, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysisCompetitorsRow
	for rows.Next() {
		var i ListAnalysisCompetitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.Aliases,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSucceededResultIDs = `-- name: ListSucceededResultIDs :many
SELECT id FROM prompt_results WHERE run_id=$1 AND status='succeeded' ORDER BY requested_at,id
`

func (q *Queries) ListSucceededResultIDs(ctx context.Context, runID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSucceededResultIDs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resultOwned = `-- name: ResultOwned :one
SELECT 1 FROM prompt_results pr JOIN monitoring_runs r ON r.id=pr.run_id
JOIN businesses b ON b.id=r.business_id WHERE pr.id = $1 AND b.account_id = $2
`

type ResultOwnedParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ResultOwned(ctx context.Context, arg ResultOwnedParams) (int32, error) {
	row := q.db.QueryRow(ctx, resultOwned, arg.ID, arg.AccountID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const runBusinessOwned = `-- name: RunBusinessOwned :one
SELECT b.id FROM monitoring_runs r JOIN businesses b ON b.id=r.business_id
WHERE r.id = $1 AND b.account_id = $2
`

type RunBusinessOwnedParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) RunBusinessOwned(ctx context.Context, arg RunBusinessOwnedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, runBusinessOwned, arg.ID, arg.AccountID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const runOwnedByBusiness = `-- name: RunOwnedByBusiness :one
SELECT 1 FROM monitoring_runs WHERE id=$1 AND business_id=$2
`

type RunOwnedByBusinessParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) RunOwnedByBusiness(ctx context.Context, arg RunOwnedByBusinessParams) (int32, error) {
	row := q.db.QueryRow(ctx, runOwnedByBusiness, arg.ID, arg.BusinessID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setAnalysisCompleted = `-- name: SetAnalysisCompleted :exec
UPDATE monitoring_runs SET analysis_completed_at=now() WHERE id=$1 AND business_id=$2
`

type SetAnalysisCompletedParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) SetAnalysisCompleted(ctx context.Context, arg SetAnalysisCompletedParams) error {
	_, err := q.db.Exec(ctx, setAnalysisCompleted, arg.ID, arg.BusinessID)
	return err
}

const upsertResultAnalysis = `-- name: UpsertResultAnalysis :exec
INSERT INTO result_analyses (prompt_result_id,sentiment,keywords,excerpts,analysis_model,extraction_version,analyzed_at)
VALUES ($1,$2,$3,$4,$5,$6,now())
ON CONFLICT (prompt_result_id) DO UPDATE SET sentiment=EXCLUDED.sentiment,keywords=EXCLUDED.keywords,
 excerpts=EXCLUDED.excerpts,analysis_model=EXCLUDED.analysis_model,
 extraction_version=EXCLUDED.extraction_version,analyzed_at=now()
`

type UpsertResultAnalysisParams struct {
	PromptResultID    uuid.UUID
	Sentiment         *string
	Keywords          []string
	Excerpts          json.RawMessage
	AnalysisModel     string
	ExtractionVersion int32
}

func (q *Queries) UpsertResultAnalysis(ctx context.Context, arg UpsertResultAnalysisParams) error {
	_, err := q.db.Exec(ctx, upsertResultAnalysis,
		arg.PromptResultID,
		arg.Sentiment,
		arg.Keywords,
		arg.Excerpts,
		arg.AnalysisModel,
		arg.ExtractionVersion,
	)
	return err
}
