// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment_replay.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listGenerationAssessments = `-- name: ListGenerationAssessments :many
SELECT practice_key, subject_key, status
FROM visibility_assessments
WHERE generation_id = $1
ORDER BY practice_key, subject_key
`

type ListGenerationAssessmentsRow struct {
	PracticeKey string
	SubjectKey  string
	Status      string
}

func (q *Queries) ListGenerationAssessments(ctx context.Context, generationID uuid.UUID) ([]ListGenerationAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listGenerationAssessments, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationAssessmentsRow
	for rows.Next() {
		var i ListGenerationAssessmentsRow
		if err := rows.Scan(&i.PracticeKey, &i.SubjectKey, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationEvidence = `-- name: ListGenerationEvidence :many
SELECT collector_key, collector_version, payload_version, checked_at, payload
FROM evidence_artifacts
WHERE generation_id = $1 AND status = 'SUCCEEDED'
ORDER BY collector_key
`

type ListGenerationEvidenceRow struct {
	CollectorKey     string
	CollectorVersion int32
	PayloadVersion   int32
	CheckedAt        time.Time
	Payload          json.RawMessage
}

// Only SUCCEEDED artifacts are replayable: a FAILED row stores a placeholder
// payload, and feeding that to an assessor would manufacture a verdict from
// evidence that was never collected.
func (q *Queries) ListGenerationEvidence(ctx context.Context, generationID uuid.UUID) ([]ListGenerationEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listGenerationEvidence, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationEvidenceRow
	for rows.Next() {
		var i ListGenerationEvidenceRow
		if err := rows.Scan(
			&i.CollectorKey,
			&i.CollectorVersion,
			&i.PayloadVersion,
			&i.CheckedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayGenerations = `-- name: ListReplayGenerations :many

SELECT g.id, g.account_id, g.business_id, g.monitoring_run_id, g.status, g.started_at
FROM assessment_generations g
WHERE ($1::uuid IS NULL OR g.business_id = $1::uuid)
  AND ($2::timestamptz IS NULL OR g.started_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR g.started_at < $3::timestamptz)
ORDER BY g.started_at, g.id
LIMIT $4::int
`

type ListReplayGenerationsParams struct {
	BusinessID     *uuid.UUID
	Since          *time.Time
	Until          *time.Time
	MaxGenerations int32
}

type ListReplayGenerationsRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	BusinessID      uuid.UUID
	MonitoringRunID uuid.UUID
	Status          string
	StartedAt       time.Time
}

// Read-only catalog for `opensight assess replay`. Nothing here writes: replay
// re-derives verdicts from evidence that was already captured and compares them
// against what was stored, so the historical record is never touched.
func (q *Queries) ListReplayGenerations(ctx context.Context, arg ListReplayGenerationsParams) ([]ListReplayGenerationsRow, error) {
	rows, err := q.db.Query(ctx, listReplayGenerations,
		arg.BusinessID,
		arg.Since,
		arg.Until,
		arg.MaxGenerations,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayGenerationsRow
	for rows.Next() {
		var i ListReplayGenerationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BusinessID,
			&i.MonitoringRunID,
			&i.Status,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
