// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competitors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const approveSuggestedAlias = `-- name: ApproveSuggestedAlias :one
UPDATE competitors co
SET suggested_aliases=array_remove(co.suggested_aliases,$1),
    aliases=CASE WHEN $1=ANY(co.aliases) THEN co.aliases ELSE array_append(co.aliases,$1) END
FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3 AND $1=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type ApproveSuggestedAliasParams struct {
	ArrayRemove interface{}
	ID          uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) ApproveSuggestedAlias(ctx context.Context, arg ApproveSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, approveSuggestedAlias, arg.ArrayRemove, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createManualCompetitor = `-- name: CreateManualCompetitor :one
INSERT INTO competitors (id,business_id,name,website,aliases,source,status)
SELECT $1,b.id,$2,$3,$4,'manual','tracked' FROM businesses b
WHERE b.id = $5 AND b.account_id = $6
RETURNING id,business_id,name,website,aliases,suggested_aliases,source,status,created_at
`

type CreateManualCompetitorParams struct {
	ID         uuid.UUID
	Name       string
	Website    *string
	Aliases    []string
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) CreateManualCompetitor(ctx context.Context, arg CreateManualCompetitorParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, createManualCompetitor,
		arg.ID,
		arg.Name,
		arg.Website,
		arg.Aliases,
		arg.BusinessID,
		arg.AccountID,
	)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const rejectSuggestedAlias = `-- name: RejectSuggestedAlias :one
UPDATE competitors co SET suggested_aliases=array_remove(co.suggested_aliases,$1)
FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3 AND $1=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type RejectSuggestedAliasParams struct {
	ArrayRemove interface{}
	ID          uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) RejectSuggestedAlias(ctx context.Context, arg RejectSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, rejectSuggestedAlias, arg.ArrayRemove, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setCompetitorStatus = `-- name: SetCompetitorStatus :one
UPDATE competitors co SET status = $1 FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type SetCompetitorStatusParams struct {
	Status    string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) SetCompetitorStatus(ctx context.Context, arg SetCompetitorStatusParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, setCompetitorStatus, arg.Status, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompetitorAliases = `-- name: UpdateCompetitorAliases :one
UPDATE competitors co SET aliases = $1 FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type UpdateCompetitorAliasesParams struct {
	Aliases   []string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) UpdateCompetitorAliases(ctx context.Context, arg UpdateCompetitorAliasesParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, updateCompetitorAliases, arg.Aliases, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
