// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competitors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const approveSuggestedAlias = `-- name: ApproveSuggestedAlias :one
UPDATE competitors co
SET suggested_aliases=array_remove(co.suggested_aliases,$1),
    aliases=CASE WHEN $1=ANY(co.aliases) THEN co.aliases ELSE array_append(co.aliases,$1) END
FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3 AND $1=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type ApproveSuggestedAliasParams struct {
	ArrayRemove interface{}
	ID          uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) ApproveSuggestedAlias(ctx context.Context, arg ApproveSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, approveSuggestedAlias, arg.ArrayRemove, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createManualCompetitor = `-- name: CreateManualCompetitor :one
INSERT INTO competitors (id,business_id,name,website,aliases,source,status)
SELECT $1,b.id,$2,$3,$4,'manual','tracked' FROM businesses b
WHERE b.id = $5 AND b.account_id = $6
RETURNING id,business_id,name,website,aliases,suggested_aliases,source,status,created_at
`

type CreateManualCompetitorParams struct {
	ID         uuid.UUID
	Name       string
	Website    *string
	Aliases    []string
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) CreateManualCompetitor(ctx context.Context, arg CreateManualCompetitorParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, createManualCompetitor,
		arg.ID,
		arg.Name,
		arg.Website,
		arg.Aliases,
		arg.BusinessID,
		arg.AccountID,
	)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompetitor = `-- name: DeleteCompetitor :exec
DELETE FROM competitors WHERE id = $1
`

func (q *Queries) DeleteCompetitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompetitor, id)
	return err
}

const loadCompetitorForClaim = `-- name: LoadCompetitorForClaim :one
SELECT co.id,co.business_id,co.name,co.aliases,b.aliases::text[] AS business_aliases
FROM competitors co JOIN businesses b ON b.id = co.business_id
WHERE co.id = $1 AND b.account_id = $2
FOR UPDATE OF co, b
`

type LoadCompetitorForClaimParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type LoadCompetitorForClaimRow struct {
	ID              uuid.UUID
	BusinessID      uuid.UUID
	Name            string
	Aliases         []string
	BusinessAliases []string
}

// Locks the business too, not just the competitor: the claim reads b.aliases,
// merges in Go, and writes the whole array back, so two concurrent claims on
// different competitors of one business would otherwise lose the first merge.
func (q *Queries) LoadCompetitorForClaim(ctx context.Context, arg LoadCompetitorForClaimParams) (LoadCompetitorForClaimRow, error) {
	row := q.db.QueryRow(ctx, loadCompetitorForClaim, arg.ID, arg.AccountID)
	var i LoadCompetitorForClaimRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Aliases,
		&i.BusinessAliases,
	)
	return i, err
}

const reassignCompetitorMentionsToSelf = `-- name: ReassignCompetitorMentionsToSelf :exec
UPDATE mentions SET subject='self',competitor_id=NULL WHERE competitor_id = $1
`

func (q *Queries) ReassignCompetitorMentionsToSelf(ctx context.Context, competitorID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, reassignCompetitorMentionsToSelf, competitorID)
	return err
}

const rejectSuggestedAlias = `-- name: RejectSuggestedAlias :one
UPDATE competitors co SET suggested_aliases=array_remove(co.suggested_aliases,$1)
FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3 AND $1=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type RejectSuggestedAliasParams struct {
	ArrayRemove interface{}
	ID          uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) RejectSuggestedAlias(ctx context.Context, arg RejectSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, rejectSuggestedAlias, arg.ArrayRemove, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setBusinessAliases = `-- name: SetBusinessAliases :exec
UPDATE businesses SET aliases = $1::text[] WHERE id = $2
`

type SetBusinessAliasesParams struct {
	Aliases    []string
	BusinessID uuid.UUID
}

func (q *Queries) SetBusinessAliases(ctx context.Context, arg SetBusinessAliasesParams) error {
	_, err := q.db.Exec(ctx, setBusinessAliases, arg.Aliases, arg.BusinessID)
	return err
}

const setCompetitorStatus = `-- name: SetCompetitorStatus :one
UPDATE competitors co SET status = $1 FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type SetCompetitorStatusParams struct {
	Status    string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) SetCompetitorStatus(ctx context.Context, arg SetCompetitorStatusParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, setCompetitorStatus, arg.Status, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompetitorAliases = `-- name: UpdateCompetitorAliases :one
UPDATE competitors co SET aliases = $1 FROM businesses b
WHERE co.id = $2 AND co.business_id=b.id AND b.account_id = $3
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type UpdateCompetitorAliasesParams struct {
	Aliases   []string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) UpdateCompetitorAliases(ctx context.Context, arg UpdateCompetitorAliasesParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, updateCompetitorAliases, arg.Aliases, arg.ID, arg.AccountID)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
