// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competitors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const approveSuggestedAlias = `-- name: ApproveSuggestedAlias :one
UPDATE competitors co
SET suggested_aliases=array_remove(co.suggested_aliases,$3),
    aliases=CASE WHEN $3=ANY(co.aliases) THEN co.aliases ELSE array_append(co.aliases,$3) END
FROM businesses b
WHERE co.id=$1 AND co.business_id=b.id AND b.tenant_id=$2 AND $3=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type ApproveSuggestedAliasParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ArrayRemove interface{}
}

func (q *Queries) ApproveSuggestedAlias(ctx context.Context, arg ApproveSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, approveSuggestedAlias, arg.ID, arg.TenantID, arg.ArrayRemove)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createManualCompetitor = `-- name: CreateManualCompetitor :one
INSERT INTO competitors (id,business_id,name,website,aliases,source,status)
SELECT $1,b.id,$4,$5,$6,'manual','tracked' FROM businesses b
WHERE b.id=$2 AND b.tenant_id=$3
RETURNING id,business_id,name,website,aliases,suggested_aliases,source,status,created_at
`

type CreateManualCompetitorParams struct {
	ID       uuid.UUID
	ID_2     uuid.UUID
	TenantID uuid.UUID
	Name     string
	Website  *string
	Aliases  []string
}

func (q *Queries) CreateManualCompetitor(ctx context.Context, arg CreateManualCompetitorParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, createManualCompetitor,
		arg.ID,
		arg.ID_2,
		arg.TenantID,
		arg.Name,
		arg.Website,
		arg.Aliases,
	)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const rejectSuggestedAlias = `-- name: RejectSuggestedAlias :one
UPDATE competitors co SET suggested_aliases=array_remove(co.suggested_aliases,$3)
FROM businesses b
WHERE co.id=$1 AND co.business_id=b.id AND b.tenant_id=$2 AND $3=ANY(co.suggested_aliases)
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type RejectSuggestedAliasParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ArrayRemove interface{}
}

func (q *Queries) RejectSuggestedAlias(ctx context.Context, arg RejectSuggestedAliasParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, rejectSuggestedAlias, arg.ID, arg.TenantID, arg.ArrayRemove)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setCompetitorStatus = `-- name: SetCompetitorStatus :one
UPDATE competitors co SET status=$3 FROM businesses b
WHERE co.id=$1 AND co.business_id=b.id AND b.tenant_id=$2
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type SetCompetitorStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Status   string
}

func (q *Queries) SetCompetitorStatus(ctx context.Context, arg SetCompetitorStatusParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, setCompetitorStatus, arg.ID, arg.TenantID, arg.Status)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompetitorAliases = `-- name: UpdateCompetitorAliases :one
UPDATE competitors co SET aliases=$3 FROM businesses b
WHERE co.id=$1 AND co.business_id=b.id AND b.tenant_id=$2
RETURNING co.id,co.business_id,co.name,co.website,co.aliases,co.suggested_aliases,co.source,co.status,co.created_at
`

type UpdateCompetitorAliasesParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Aliases  []string
}

func (q *Queries) UpdateCompetitorAliases(ctx context.Context, arg UpdateCompetitorAliasesParams) (Competitor, error) {
	row := q.db.QueryRow(ctx, updateCompetitorAliases, arg.ID, arg.TenantID, arg.Aliases)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.SuggestedAliases,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
