// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAdvisoryLock = `-- name: AcquireAdvisoryLock :exec
SELECT pg_advisory_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireAdvisoryLock(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryLock, hashtextextended)
	return err
}

const activateBusiness = `-- name: ActivateBusiness :one
UPDATE businesses
SET name = $2, aliases = $3, category = $4, services = $5, location = $6,
    status = 'active', activated_at = $7,
    generation_id = NULL, generation_job_id = NULL,
    generation_status = NULL, generation_stage = NULL
WHERE id = $1
RETURNING id, account_id, status, name, website, aliases, category, services, location, created_at, activated_at,
          generation_id, generation_job_id, generation_status, generation_stage
`

type ActivateBusinessParams struct {
	ID          uuid.UUID
	Name        string
	Aliases     []string
	Category    *string
	Services    json.RawMessage
	Location    *json.RawMessage
	ActivatedAt *time.Time
}

func (q *Queries) ActivateBusiness(ctx context.Context, arg ActivateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, activateBusiness,
		arg.ID,
		arg.Name,
		arg.Aliases,
		arg.Category,
		arg.Services,
		arg.Location,
		arg.ActivatedAt,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.GenerationID,
		&i.GenerationJobID,
		&i.GenerationStatus,
		&i.GenerationStage,
	)
	return i, err
}

const businessOwned = `-- name: BusinessOwned :one
SELECT 1 FROM businesses WHERE id = $1 AND account_id = $2
`

type BusinessOwnedParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) BusinessOwned(ctx context.Context, arg BusinessOwnedParams) (int32, error) {
	row := q.db.QueryRow(ctx, businessOwned, arg.ID, arg.AccountID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAccountOwners = `-- name: CountAccountOwners :one
SELECT count(*) FROM account_memberships WHERE account_id = $1 AND role = 'owner'
`

func (q *Queries) CountAccountOwners(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountOwners, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivePrompts = `-- name: CountActivePrompts :one
SELECT count(*) FROM prompts WHERE business_id = $1 AND status = 'active'
`

func (q *Queries) CountActivePrompts(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePrompts, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountMembership = `-- name: DeleteAccountMembership :execrows
DELETE FROM account_memberships WHERE account_id = $1 AND user_id = $2
`

type DeleteAccountMembershipParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteAccountMembership(ctx context.Context, arg DeleteAccountMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountMembership, arg.AccountID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND expires_at <= now()
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const discardPendingProposal = `-- name: DiscardPendingProposal :exec
UPDATE profile_proposals SET status='discarded',resolved_at=now()
WHERE business_id=$1 AND status='pending'
`

func (q *Queries) DiscardPendingProposal(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, discardPendingProposal, businessID)
	return err
}

const finishBusinessGeneration = `-- name: FinishBusinessGeneration :execrows
UPDATE businesses SET generation_status = $1, generation_stage = NULL
WHERE id = $2 AND generation_id = $3
  AND status = 'draft' AND generation_status = 'generating'
`

type FinishBusinessGenerationParams struct {
	Status       *string
	BusinessID   uuid.UUID
	GenerationID *uuid.UUID
}

func (q *Queries) FinishBusinessGeneration(ctx context.Context, arg FinishBusinessGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishBusinessGeneration, arg.Status, arg.BusinessID, arg.GenerationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const generationIsCurrent = `-- name: GenerationIsCurrent :one
SELECT EXISTS(
  SELECT 1 FROM businesses
  WHERE id = $1 AND generation_id = $2
    AND status = 'draft' AND generation_status = 'generating'
)
`

type GenerationIsCurrentParams struct {
	BusinessID   uuid.UUID
	GenerationID *uuid.UUID
}

func (q *Queries) GenerationIsCurrent(ctx context.Context, arg GenerationIsCurrentParams) (bool, error) {
	row := q.db.QueryRow(ctx, generationIsCurrent, arg.BusinessID, arg.GenerationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, slug, created_at FROM accounts WHERE id = $1
`

type GetAccountByIDRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountContextBySlug = `-- name: GetAccountContextBySlug :one
SELECT a.id AS account_id, a.name, a.slug, am.role,
       sub.plan_code, sub.comped, sub.stripe_subscription_id,
       sub.stripe_status, sub.past_due_since
FROM accounts a
LEFT JOIN account_memberships am ON am.account_id = a.id AND am.user_id = $1
LEFT JOIN subscriptions sub ON sub.account_id = a.id
WHERE a.slug = $2
`

type GetAccountContextBySlugParams struct {
	UserID uuid.UUID
	Slug   string
}

type GetAccountContextBySlugRow struct {
	AccountID            uuid.UUID
	Name                 string
	Slug                 string
	Role                 *string
	PlanCode             *string
	Comped               pgtype.Bool
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
}

// Membership is a LEFT JOIN so the row still comes back for a non-member,
// with a NULL role. Only the platform owner is admitted on such a row
// (store.ResolveAccountSession); everyone else is rejected as not found.
func (q *Queries) GetAccountContextBySlug(ctx context.Context, arg GetAccountContextBySlugParams) (GetAccountContextBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAccountContextBySlug, arg.UserID, arg.Slug)
	var i GetAccountContextBySlugRow
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Slug,
		&i.Role,
		&i.PlanCode,
		&i.Comped,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
	)
	return i, err
}

const getAccountMembership = `-- name: GetAccountMembership :one
SELECT account_id, user_id, role, created_at FROM account_memberships
WHERE account_id = $1 AND user_id = $2
`

type GetAccountMembershipParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetAccountMembership(ctx context.Context, arg GetAccountMembershipParams) (AccountMembership, error) {
	row := q.db.QueryRow(ctx, getAccountMembership, arg.AccountID, arg.UserID)
	var i AccountMembership
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, account_id, status, name, website, aliases, category, services, location, created_at, activated_at,
       generation_id, generation_job_id, generation_status, generation_stage
FROM businesses WHERE id = $1 AND account_id = $2
`

type GetBusinessParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) GetBusiness(ctx context.Context, arg GetBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, arg.ID, arg.AccountID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.GenerationID,
		&i.GenerationJobID,
		&i.GenerationStatus,
		&i.GenerationStage,
	)
	return i, err
}

const getPendingProposal = `-- name: GetPendingProposal :one
SELECT id,business_id,payload,status,created_at,resolved_at
FROM profile_proposals WHERE business_id=$1 AND status='pending'
`

func (q *Queries) GetPendingProposal(ctx context.Context, businessID uuid.UUID) (ProfileProposal, error) {
	row := q.db.QueryRow(ctx, getPendingProposal, businessID)
	var i ProfileProposal
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPrompt = `-- name: GetPrompt :one
SELECT pr.id, pr.business_id, pr.text, pr.status, pr.replaces_prompt_id, pr.created_at
FROM prompts pr JOIN businesses b ON b.id = pr.business_id
WHERE pr.id = $1 AND b.account_id = $2
`

type GetPromptParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetPromptRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) GetPrompt(ctx context.Context, arg GetPromptParams) (GetPromptRow, error) {
	row := q.db.QueryRow(ctx, getPrompt, arg.ID, arg.AccountID)
	var i GetPromptRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Text,
		&i.Status,
		&i.ReplacesPromptID,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT u.id, u.email, s.expires_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	ID        uuid.UUID
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.Email, &i.ExpiresAt)
	return i, err
}

const getSubscriptionByAccount = `-- name: GetSubscriptionByAccount :one
SELECT account_id, plan_code, stripe_customer_id, stripe_subscription_id,
       stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end,
       created_at, updated_at
FROM subscriptions WHERE account_id = $1
`

func (q *Queries) GetSubscriptionByAccount(ctx context.Context, accountID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByAccount, accountID)
	var i Subscription
	err := row.Scan(
		&i.AccountID,
		&i.PlanCode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
		&i.Comped,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByCustomer = `-- name: GetSubscriptionByCustomer :one
SELECT account_id, plan_code, stripe_customer_id, stripe_subscription_id,
       stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end,
       created_at, updated_at
FROM subscriptions WHERE stripe_customer_id = $1
`

func (q *Queries) GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.AccountID,
		&i.PlanCode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
		&i.Comped,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, google_sub FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	Email     string
	GoogleSub *string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.GoogleSub)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, google_sub FROM users WHERE google_sub = $1
`

type GetUserByGoogleSubRow struct {
	ID        uuid.UUID
	Email     string
	GoogleSub *string
}

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (GetUserByGoogleSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i GetUserByGoogleSubRow
	err := row.Scan(&i.ID, &i.Email, &i.GoogleSub)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (id, name, slug) VALUES ($1, $2, $3) RETURNING created_at
`

type InsertAccountParams struct {
	ID   uuid.UUID
	Name string
	Slug string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertAccount, arg.ID, arg.Name, arg.Slug)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertAccountMembership = `-- name: InsertAccountMembership :one
INSERT INTO account_memberships (account_id, user_id, role)
VALUES ($1, $2, $3) RETURNING created_at
`

type InsertAccountMembershipParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) InsertAccountMembership(ctx context.Context, arg InsertAccountMembershipParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertAccountMembership, arg.AccountID, arg.UserID, arg.Role)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertActivePrompt = `-- name: InsertActivePrompt :one
INSERT INTO prompts (id, business_id, text, status, replaces_prompt_id)
VALUES ($1, $2, $3, 'active', $4) RETURNING created_at
`

type InsertActivePromptParams struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	ReplacesPromptID *uuid.UUID
}

func (q *Queries) InsertActivePrompt(ctx context.Context, arg InsertActivePromptParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertActivePrompt,
		arg.ID,
		arg.BusinessID,
		arg.Text,
		arg.ReplacesPromptID,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertBusiness = `-- name: InsertBusiness :one
INSERT INTO businesses (
  id, account_id, status, name, website, aliases, category, services, location, activated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING created_at
`

type InsertBusinessParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Status      string
	Name        string
	Website     *string
	Aliases     []string
	Category    *string
	Services    json.RawMessage
	Location    *json.RawMessage
	ActivatedAt *time.Time
}

func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertBusiness,
		arg.ID,
		arg.AccountID,
		arg.Status,
		arg.Name,
		arg.Website,
		arg.Aliases,
		arg.Category,
		arg.Services,
		arg.Location,
		arg.ActivatedAt,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertPendingProposal = `-- name: InsertPendingProposal :one
INSERT INTO profile_proposals (id,business_id,payload,status)
VALUES ($1,$2,$3,'pending') RETURNING created_at
`

type InsertPendingProposalParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	Payload    json.RawMessage
}

func (q *Queries) InsertPendingProposal(ctx context.Context, arg InsertPendingProposalParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertPendingProposal, arg.ID, arg.BusinessID, arg.Payload)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (account_id, plan_code, comped) VALUES ($1, $2, $3)
`

type InsertSubscriptionParams struct {
	AccountID uuid.UUID
	PlanCode  string
	Comped    bool
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription, arg.AccountID, arg.PlanCode, arg.Comped)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, email, google_sub) VALUES ($1, $2, $3) RETURNING created_at
`

type InsertUserParams struct {
	ID        uuid.UUID
	Email     string
	GoogleSub *string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Email, arg.GoogleSub)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const installBusinessGeneration = `-- name: InstallBusinessGeneration :one
UPDATE businesses
SET website = $1,
    generation_id = $2,
    generation_job_id = $3,
    generation_status = 'generating',
    generation_stage = 'fetching_site'
WHERE id = $4 AND account_id = $5 AND status = 'draft'
RETURNING generation_job_id
`

type InstallBusinessGenerationParams struct {
	Website         *string
	GenerationID    *uuid.UUID
	GenerationJobID *int64
	BusinessID      uuid.UUID
	AccountID       uuid.UUID
}

func (q *Queries) InstallBusinessGeneration(ctx context.Context, arg InstallBusinessGenerationParams) (*int64, error) {
	row := q.db.QueryRow(ctx, installBusinessGeneration,
		arg.Website,
		arg.GenerationID,
		arg.GenerationJobID,
		arg.BusinessID,
		arg.AccountID,
	)
	var generation_job_id *int64
	err := row.Scan(&generation_job_id)
	return generation_job_id, err
}

const listAccountMembers = `-- name: ListAccountMembers :many
SELECT u.id AS user_id, u.email, u.google_sub, am.role, am.created_at
FROM account_memberships am JOIN users u ON u.id = am.user_id
WHERE am.account_id = $1 ORDER BY lower(u.email), u.id
`

type ListAccountMembersRow struct {
	UserID    uuid.UUID
	Email     string
	GoogleSub *string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) ListAccountMembers(ctx context.Context, accountID uuid.UUID) ([]ListAccountMembersRow, error) {
	rows, err := q.db.Query(ctx, listAccountMembers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountMembersRow
	for rows.Next() {
		var i ListAccountMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.GoogleSub,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountMembershipsForUser = `-- name: ListAccountMembershipsForUser :many
SELECT a.id AS account_id, a.name, a.slug, am.role, am.created_at
FROM account_memberships am JOIN accounts a ON a.id = am.account_id
WHERE am.user_id = $1 ORDER BY a.name, a.id
`

type ListAccountMembershipsForUserRow struct {
	AccountID uuid.UUID
	Name      string
	Slug      string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) ListAccountMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListAccountMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountMembershipsForUserRow
	for rows.Next() {
		var i ListAccountMembershipsForUserRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePrompts = `-- name: ListActivePrompts :many
SELECT id, business_id, text, status, replaces_prompt_id, created_at
FROM prompts WHERE business_id = $1 AND status = 'active' ORDER BY created_at
`

type ListActivePromptsRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) ListActivePrompts(ctx context.Context, businessID uuid.UUID) ([]ListActivePromptsRow, error) {
	rows, err := q.db.Query(ctx, listActivePrompts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePromptsRow
	for rows.Next() {
		var i ListActivePromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Text,
			&i.Status,
			&i.ReplacesPromptID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT a.id AS account_id, a.name, a.slug, am.role, am.created_at
FROM accounts a
LEFT JOIN account_memberships am ON am.account_id = a.id AND am.user_id = $1
ORDER BY a.name, a.id
`

type ListAllAccountsRow struct {
	AccountID uuid.UUID
	Name      string
	Slug      string
	Role      *string
	CreatedAt *time.Time
}

// Every account on the platform, carrying @user_id's own role where they are
// a member. Platform-owner only (see api.isPlatformOwner).
func (q *Queries) ListAllAccounts(ctx context.Context, userID uuid.UUID) ([]ListAllAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAllAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAccountsRow
	for rows.Next() {
		var i ListAllAccountsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, account_id, status, name, website, aliases, category, services, location, created_at, activated_at,
       generation_id, generation_job_id, generation_status, generation_stage
FROM businesses WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) ListBusinesses(ctx context.Context, accountID uuid.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinesses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Status,
			&i.Name,
			&i.Website,
			&i.Aliases,
			&i.Category,
			&i.Services,
			&i.Location,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.GenerationID,
			&i.GenerationJobID,
			&i.GenerationStatus,
			&i.GenerationStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringCandidates = `-- name: ListMonitoringCandidates :many
SELECT b.id, b.account_id, b.activated_at, s.plan_code, s.comped,
       s.stripe_subscription_id, s.stripe_status, s.past_due_since
FROM businesses b
JOIN subscriptions s ON s.account_id = b.account_id
WHERE b.status = 'active' AND b.activated_at IS NOT NULL
`

type ListMonitoringCandidatesRow struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	ActivatedAt          *time.Time
	PlanCode             string
	Comped               bool
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
}

func (q *Queries) ListMonitoringCandidates(ctx context.Context) ([]ListMonitoringCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMonitoringCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitoringCandidatesRow
	for rows.Next() {
		var i ListMonitoringCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ActivatedAt,
			&i.PlanCode,
			&i.Comped,
			&i.StripeSubscriptionID,
			&i.StripeStatus,
			&i.PastDueSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :one
SELECT id FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockBusinessPlanCode = `-- name: LockBusinessPlanCode :one
SELECT s.plan_code
FROM businesses b JOIN subscriptions s ON s.account_id = b.account_id
WHERE b.id = $1 AND b.account_id = $2 FOR UPDATE OF b
`

type LockBusinessPlanCodeParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) LockBusinessPlanCode(ctx context.Context, arg LockBusinessPlanCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, lockBusinessPlanCode, arg.ID, arg.AccountID)
	var plan_code string
	err := row.Scan(&plan_code)
	return plan_code, err
}

const lockDraftBusiness = `-- name: LockDraftBusiness :one
SELECT status FROM businesses WHERE id = $1 AND account_id = $2 FOR UPDATE
`

type LockDraftBusinessParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) LockDraftBusiness(ctx context.Context, arg LockDraftBusinessParams) (string, error) {
	row := q.db.QueryRow(ctx, lockDraftBusiness, arg.ID, arg.AccountID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockPromptForReplace = `-- name: LockPromptForReplace :one
SELECT pr.id, pr.business_id, pr.text, pr.status, pr.replaces_prompt_id, pr.created_at
FROM prompts pr JOIN businesses b ON b.id = pr.business_id
WHERE pr.id = $1 AND b.account_id = $2 FOR UPDATE OF pr
`

type LockPromptForReplaceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type LockPromptForReplaceRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) LockPromptForReplace(ctx context.Context, arg LockPromptForReplaceParams) (LockPromptForReplaceRow, error) {
	row := q.db.QueryRow(ctx, lockPromptForReplace, arg.ID, arg.AccountID)
	var i LockPromptForReplaceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Text,
		&i.Status,
		&i.ReplacesPromptID,
		&i.CreatedAt,
	)
	return i, err
}

const markProposalApplied = `-- name: MarkProposalApplied :exec
UPDATE profile_proposals SET status = 'applied', resolved_at = now()
WHERE business_id = $1 AND status = 'pending'
`

func (q *Queries) MarkProposalApplied(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markProposalApplied, businessID)
	return err
}

const releaseAdvisoryLock = `-- name: ReleaseAdvisoryLock :one
SELECT pg_advisory_unlock(hashtextextended($1, 0))
`

func (q *Queries) ReleaseAdvisoryLock(ctx context.Context, hashtextextended string) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLock, hashtextextended)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const renameAccount = `-- name: RenameAccount :exec
UPDATE accounts SET name = $2 WHERE id = $1
`

type RenameAccountParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameAccount(ctx context.Context, arg RenameAccountParams) error {
	_, err := q.db.Exec(ctx, renameAccount, arg.ID, arg.Name)
	return err
}

const resolveAccountID = `-- name: ResolveAccountID :one
SELECT account_id FROM businesses WHERE id = $1
`

func (q *Queries) ResolveAccountID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveAccountID, id)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const retirePrompt = `-- name: RetirePrompt :exec
UPDATE prompts SET status = 'retired', retired_at = now() WHERE id = $1
`

func (q *Queries) RetirePrompt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, retirePrompt, id)
	return err
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :one
UPDATE subscriptions
SET stripe_customer_id=COALESCE(stripe_customer_id,$2),
    updated_at=CASE WHEN stripe_customer_id IS NULL THEN now() ELSE updated_at END
WHERE account_id=$1 RETURNING stripe_customer_id
`

type SetStripeCustomerIDParams struct {
	AccountID        uuid.UUID
	StripeCustomerID *string
}

func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) (*string, error) {
	row := q.db.QueryRow(ctx, setStripeCustomerID, arg.AccountID, arg.StripeCustomerID)
	var stripe_customer_id *string
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const setUserGoogleSub = `-- name: SetUserGoogleSub :exec
UPDATE users SET google_sub = $2 WHERE id = $1
`

type SetUserGoogleSubParams struct {
	ID        uuid.UUID
	GoogleSub *string
}

func (q *Queries) SetUserGoogleSub(ctx context.Context, arg SetUserGoogleSubParams) error {
	_, err := q.db.Exec(ctx, setUserGoogleSub, arg.ID, arg.GoogleSub)
	return err
}

const updateAccountMembershipRole = `-- name: UpdateAccountMembershipRole :execrows
UPDATE account_memberships SET role = $3 WHERE account_id = $1 AND user_id = $2
`

type UpdateAccountMembershipRoleParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) UpdateAccountMembershipRole(ctx context.Context, arg UpdateAccountMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountMembershipRole, arg.AccountID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateActiveBusinessProfile = `-- name: UpdateActiveBusinessProfile :one
UPDATE businesses
SET name = CASE WHEN $1::bool THEN $2 ELSE name END,
    website = CASE WHEN $3::bool THEN $4 ELSE website END,
    aliases = CASE WHEN $5::bool THEN $6::text[] ELSE aliases END,
    category = CASE WHEN $7::bool THEN $8 ELSE category END,
    services = CASE WHEN $9::bool THEN $10::jsonb ELSE services END,
    location = CASE WHEN $11::bool THEN $12::jsonb ELSE location END
WHERE id = $13 AND account_id = $14 AND status = 'active'
RETURNING id, account_id, status, name, website, aliases, category, services, location, created_at, activated_at,
          generation_id, generation_job_id, generation_status, generation_stage
`

type UpdateActiveBusinessProfileParams struct {
	NameSet     bool
	Name        string
	WebsiteSet  bool
	Website     *string
	AliasesSet  bool
	Aliases     []string
	CategorySet bool
	Category    *string
	ServicesSet bool
	Services    json.RawMessage
	LocationSet bool
	Location    json.RawMessage
	BusinessID  uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) UpdateActiveBusinessProfile(ctx context.Context, arg UpdateActiveBusinessProfileParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateActiveBusinessProfile,
		arg.NameSet,
		arg.Name,
		arg.WebsiteSet,
		arg.Website,
		arg.AliasesSet,
		arg.Aliases,
		arg.CategorySet,
		arg.Category,
		arg.ServicesSet,
		arg.Services,
		arg.LocationSet,
		arg.Location,
		arg.BusinessID,
		arg.AccountID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.GenerationID,
		&i.GenerationJobID,
		&i.GenerationStatus,
		&i.GenerationStage,
	)
	return i, err
}

const updateBusinessGenerationStage = `-- name: UpdateBusinessGenerationStage :execrows
UPDATE businesses SET generation_stage = $1
WHERE id = $2 AND generation_id = $3
  AND status = 'draft' AND generation_status = 'generating'
`

type UpdateBusinessGenerationStageParams struct {
	Stage        *string
	BusinessID   uuid.UUID
	GenerationID *uuid.UUID
}

func (q *Queries) UpdateBusinessGenerationStage(ctx context.Context, arg UpdateBusinessGenerationStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBusinessGenerationStage, arg.Stage, arg.BusinessID, arg.GenerationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftBusinessWebsite = `-- name: UpdateDraftBusinessWebsite :one
UPDATE businesses
SET website = $1
WHERE id = $2 AND account_id = $3 AND status = 'draft'
RETURNING id, account_id, status, name, website, aliases, category, services, location, created_at, activated_at,
          generation_id, generation_job_id, generation_status, generation_stage
`

type UpdateDraftBusinessWebsiteParams struct {
	Website    *string
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) UpdateDraftBusinessWebsite(ctx context.Context, arg UpdateDraftBusinessWebsiteParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateDraftBusinessWebsite, arg.Website, arg.BusinessID, arg.AccountID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.GenerationID,
		&i.GenerationJobID,
		&i.GenerationStatus,
		&i.GenerationStage,
	)
	return i, err
}

const upsertAccountMembership = `-- name: UpsertAccountMembership :one
INSERT INTO account_memberships (account_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, user_id) DO UPDATE SET role = account_memberships.role
RETURNING role, created_at
`

type UpsertAccountMembershipParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

type UpsertAccountMembershipRow struct {
	Role      string
	CreatedAt time.Time
}

func (q *Queries) UpsertAccountMembership(ctx context.Context, arg UpsertAccountMembershipParams) (UpsertAccountMembershipRow, error) {
	row := q.db.QueryRow(ctx, upsertAccountMembership, arg.AccountID, arg.UserID, arg.Role)
	var i UpsertAccountMembershipRow
	err := row.Scan(&i.Role, &i.CreatedAt)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (
  account_id, plan_code, stripe_customer_id, stripe_subscription_id,
  stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (account_id) DO UPDATE SET
  plan_code=EXCLUDED.plan_code, stripe_customer_id=EXCLUDED.stripe_customer_id,
  stripe_subscription_id=EXCLUDED.stripe_subscription_id, stripe_status=EXCLUDED.stripe_status,
  past_due_since=EXCLUDED.past_due_since, comped=EXCLUDED.comped,
  current_period_end=EXCLUDED.current_period_end, cancel_at_period_end=EXCLUDED.cancel_at_period_end,
  updated_at=now()
`

type UpsertSubscriptionParams struct {
	AccountID            uuid.UUID
	PlanCode             string
	StripeCustomerID     *string
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
	Comped               bool
	CurrentPeriodEnd     *time.Time
	CancelAtPeriodEnd    bool
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.AccountID,
		arg.PlanCode,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StripeStatus,
		arg.PastDueSince,
		arg.Comped,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (id, email) VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, google_sub, created_at
`

type UpsertUserByEmailParams struct {
	ID    uuid.UUID
	Email string
}

type UpsertUserByEmailRow struct {
	ID        uuid.UUID
	Email     string
	GoogleSub *string
	CreatedAt time.Time
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, arg.ID, arg.Email)
	var i UpsertUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleSub,
		&i.CreatedAt,
	)
	return i, err
}
