// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAdvisoryLock = `-- name: AcquireAdvisoryLock :exec
SELECT pg_advisory_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireAdvisoryLock(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryLock, hashtextextended)
	return err
}

const activateBusiness = `-- name: ActivateBusiness :one
UPDATE businesses
SET name = $2, aliases = $3, category = $4, services = $5, location = $6,
    status = 'active', activated_at = $7
WHERE id = $1
RETURNING id, tenant_id, status, name, website, aliases, category, services, location, created_at, activated_at
`

type ActivateBusinessParams struct {
	ID          uuid.UUID
	Name        string
	Aliases     []string
	Category    *string
	Services    json.RawMessage
	Location    *json.RawMessage
	ActivatedAt *time.Time
}

func (q *Queries) ActivateBusiness(ctx context.Context, arg ActivateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, activateBusiness,
		arg.ID,
		arg.Name,
		arg.Aliases,
		arg.Category,
		arg.Services,
		arg.Location,
		arg.ActivatedAt,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const businessOwned = `-- name: BusinessOwned :one
SELECT 1 FROM businesses WHERE id = $1 AND tenant_id = $2
`

type BusinessOwnedParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) BusinessOwned(ctx context.Context, arg BusinessOwnedParams) (int32, error) {
	row := q.db.QueryRow(ctx, businessOwned, arg.ID, arg.TenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countActivePrompts = `-- name: CountActivePrompts :one
SELECT count(*) FROM prompts WHERE business_id = $1 AND status = 'active'
`

func (q *Queries) CountActivePrompts(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePrompts, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND expires_at <= now()
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const discardPendingProposal = `-- name: DiscardPendingProposal :exec
UPDATE profile_proposals SET status='discarded',resolved_at=now()
WHERE business_id=$1 AND status='pending'
`

func (q *Queries) DiscardPendingProposal(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, discardPendingProposal, businessID)
	return err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, tenant_id, status, name, website, aliases, category, services, location, created_at, activated_at
FROM businesses WHERE id = $1 AND tenant_id = $2
`

type GetBusinessParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetBusiness(ctx context.Context, arg GetBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, arg.ID, arg.TenantID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getPendingProposal = `-- name: GetPendingProposal :one
SELECT id,business_id,payload,status,created_at,resolved_at
FROM profile_proposals WHERE business_id=$1 AND status='pending'
`

func (q *Queries) GetPendingProposal(ctx context.Context, businessID uuid.UUID) (ProfileProposal, error) {
	row := q.db.QueryRow(ctx, getPendingProposal, businessID)
	var i ProfileProposal
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPrompt = `-- name: GetPrompt :one
SELECT pr.id, pr.business_id, pr.text, pr.status, pr.replaces_prompt_id, pr.created_at
FROM prompts pr JOIN businesses b ON b.id = pr.business_id
WHERE pr.id = $1 AND b.tenant_id = $2
`

type GetPromptParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetPromptRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) GetPrompt(ctx context.Context, arg GetPromptParams) (GetPromptRow, error) {
	row := q.db.QueryRow(ctx, getPrompt, arg.ID, arg.TenantID)
	var i GetPromptRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Text,
		&i.Status,
		&i.ReplacesPromptID,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT u.id, u.tenant_id, u.email, t.name, s.expires_at,
       sub.plan_code, sub.comped, sub.stripe_subscription_id, sub.stripe_status, sub.past_due_since
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN tenants t ON t.id = u.tenant_id
LEFT JOIN subscriptions sub ON sub.tenant_id = u.tenant_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	ID                   uuid.UUID
	TenantID             uuid.UUID
	Email                string
	Name                 string
	ExpiresAt            time.Time
	PlanCode             *string
	Comped               pgtype.Bool
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
}

// LEFT JOIN deliberately, not INNER: a missing subscriptions row must surface
// to the caller as an explicit error, not silently masquerade as an
// expired/absent session by disappearing from the result set.
func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.ExpiresAt,
		&i.PlanCode,
		&i.Comped,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
	)
	return i, err
}

const getSubscriptionByCustomer = `-- name: GetSubscriptionByCustomer :one
SELECT tenant_id, plan_code, stripe_customer_id, stripe_subscription_id,
       stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end,
       created_at, updated_at
FROM subscriptions WHERE stripe_customer_id = $1
`

func (q *Queries) GetSubscriptionByCustomer(ctx context.Context, stripeCustomerID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.TenantID,
		&i.PlanCode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
		&i.Comped,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByTenant = `-- name: GetSubscriptionByTenant :one
SELECT tenant_id, plan_code, stripe_customer_id, stripe_subscription_id,
       stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end,
       created_at, updated_at
FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) GetSubscriptionByTenant(ctx context.Context, tenantID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByTenant, tenantID)
	var i Subscription
	err := row.Scan(
		&i.TenantID,
		&i.PlanCode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
		&i.PastDueSince,
		&i.Comped,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.tenant_id, u.email, t.name, u.google_sub
FROM users u JOIN tenants t ON t.id = u.tenant_id WHERE u.email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	Name      string
	GoogleSub *string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.GoogleSub,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT u.id, u.tenant_id, u.email, t.name, u.google_sub
FROM users u JOIN tenants t ON t.id = u.tenant_id WHERE u.google_sub = $1
`

type GetUserByGoogleSubRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	Name      string
	GoogleSub *string
}

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (GetUserByGoogleSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i GetUserByGoogleSubRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.GoogleSub,
	)
	return i, err
}

const insertActivePrompt = `-- name: InsertActivePrompt :one
INSERT INTO prompts (id, business_id, text, status, replaces_prompt_id)
VALUES ($1, $2, $3, 'active', $4) RETURNING created_at
`

type InsertActivePromptParams struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	ReplacesPromptID *uuid.UUID
}

func (q *Queries) InsertActivePrompt(ctx context.Context, arg InsertActivePromptParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertActivePrompt,
		arg.ID,
		arg.BusinessID,
		arg.Text,
		arg.ReplacesPromptID,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertBusiness = `-- name: InsertBusiness :one
INSERT INTO businesses (
  id, tenant_id, status, name, website, aliases, category, services, location, activated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING created_at
`

type InsertBusinessParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Status      string
	Name        string
	Website     *string
	Aliases     []string
	Category    *string
	Services    json.RawMessage
	Location    *json.RawMessage
	ActivatedAt *time.Time
}

func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertBusiness,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Name,
		arg.Website,
		arg.Aliases,
		arg.Category,
		arg.Services,
		arg.Location,
		arg.ActivatedAt,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertPendingProposal = `-- name: InsertPendingProposal :one
INSERT INTO profile_proposals (id,business_id,payload,status)
VALUES ($1,$2,$3,'pending') RETURNING created_at
`

type InsertPendingProposalParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	Payload    json.RawMessage
}

func (q *Queries) InsertPendingProposal(ctx context.Context, arg InsertPendingProposalParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertPendingProposal, arg.ID, arg.BusinessID, arg.Payload)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (tenant_id, plan_code, comped) VALUES ($1, $2, $3)
`

type InsertSubscriptionParams struct {
	TenantID uuid.UUID
	PlanCode string
	Comped   bool
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription, arg.TenantID, arg.PlanCode, arg.Comped)
	return err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (id, name) VALUES ($1, $2) RETURNING created_at
`

type InsertTenantParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertTenant, arg.ID, arg.Name)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, tenant_id, email, google_sub)
VALUES ($1, $2, $3, $4) RETURNING created_at
`

type InsertUserParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	GoogleSub *string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.GoogleSub,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listActivePrompts = `-- name: ListActivePrompts :many
SELECT id, business_id, text, status, replaces_prompt_id, created_at
FROM prompts WHERE business_id = $1 AND status = 'active' ORDER BY created_at
`

type ListActivePromptsRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) ListActivePrompts(ctx context.Context, businessID uuid.UUID) ([]ListActivePromptsRow, error) {
	rows, err := q.db.Query(ctx, listActivePrompts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePromptsRow
	for rows.Next() {
		var i ListActivePromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Text,
			&i.Status,
			&i.ReplacesPromptID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, tenant_id, status, name, website, aliases, category, services, location, created_at, activated_at
FROM businesses WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListBusinesses(ctx context.Context, tenantID uuid.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinesses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.Name,
			&i.Website,
			&i.Aliases,
			&i.Category,
			&i.Services,
			&i.Location,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBusinessPlanCode = `-- name: LockBusinessPlanCode :one
SELECT s.plan_code
FROM businesses b JOIN subscriptions s ON s.tenant_id = b.tenant_id
WHERE b.id = $1 AND b.tenant_id = $2 FOR UPDATE OF b
`

type LockBusinessPlanCodeParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) LockBusinessPlanCode(ctx context.Context, arg LockBusinessPlanCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, lockBusinessPlanCode, arg.ID, arg.TenantID)
	var plan_code string
	err := row.Scan(&plan_code)
	return plan_code, err
}

const lockDraftBusiness = `-- name: LockDraftBusiness :one
SELECT status FROM businesses WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type LockDraftBusinessParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) LockDraftBusiness(ctx context.Context, arg LockDraftBusinessParams) (string, error) {
	row := q.db.QueryRow(ctx, lockDraftBusiness, arg.ID, arg.TenantID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockPromptForReplace = `-- name: LockPromptForReplace :one
SELECT pr.id, pr.business_id, pr.text, pr.status, pr.replaces_prompt_id, pr.created_at
FROM prompts pr JOIN businesses b ON b.id = pr.business_id
WHERE pr.id = $1 AND b.tenant_id = $2 FOR UPDATE OF pr
`

type LockPromptForReplaceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type LockPromptForReplaceRow struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) LockPromptForReplace(ctx context.Context, arg LockPromptForReplaceParams) (LockPromptForReplaceRow, error) {
	row := q.db.QueryRow(ctx, lockPromptForReplace, arg.ID, arg.TenantID)
	var i LockPromptForReplaceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Text,
		&i.Status,
		&i.ReplacesPromptID,
		&i.CreatedAt,
	)
	return i, err
}

const markProposalApplied = `-- name: MarkProposalApplied :exec
UPDATE profile_proposals SET status = 'applied', resolved_at = now()
WHERE business_id = $1 AND status = 'pending'
`

func (q *Queries) MarkProposalApplied(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markProposalApplied, businessID)
	return err
}

const releaseAdvisoryLock = `-- name: ReleaseAdvisoryLock :one
SELECT pg_advisory_unlock(hashtextextended($1, 0))
`

func (q *Queries) ReleaseAdvisoryLock(ctx context.Context, hashtextextended string) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLock, hashtextextended)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const renameTenant = `-- name: RenameTenant :exec
UPDATE tenants SET name = $2 WHERE id = $1
`

type RenameTenantParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameTenant(ctx context.Context, arg RenameTenantParams) error {
	_, err := q.db.Exec(ctx, renameTenant, arg.ID, arg.Name)
	return err
}

const resolveTenantID = `-- name: ResolveTenantID :one
SELECT tenant_id FROM businesses WHERE id = $1
`

func (q *Queries) ResolveTenantID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveTenantID, id)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const retirePrompt = `-- name: RetirePrompt :exec
UPDATE prompts SET status = 'retired', retired_at = now() WHERE id = $1
`

func (q *Queries) RetirePrompt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, retirePrompt, id)
	return err
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :one
UPDATE subscriptions
SET stripe_customer_id=COALESCE(stripe_customer_id,$2),
    updated_at=CASE WHEN stripe_customer_id IS NULL THEN now() ELSE updated_at END
WHERE tenant_id=$1 RETURNING stripe_customer_id
`

type SetStripeCustomerIDParams struct {
	TenantID         uuid.UUID
	StripeCustomerID *string
}

func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) (*string, error) {
	row := q.db.QueryRow(ctx, setStripeCustomerID, arg.TenantID, arg.StripeCustomerID)
	var stripe_customer_id *string
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const setUserGoogleSub = `-- name: SetUserGoogleSub :exec
UPDATE users SET google_sub = $2 WHERE id = $1
`

type SetUserGoogleSubParams struct {
	ID        uuid.UUID
	GoogleSub *string
}

func (q *Queries) SetUserGoogleSub(ctx context.Context, arg SetUserGoogleSubParams) error {
	_, err := q.db.Exec(ctx, setUserGoogleSub, arg.ID, arg.GoogleSub)
	return err
}

const updateActiveBusinessProfile = `-- name: UpdateActiveBusinessProfile :one
UPDATE businesses
SET name = CASE WHEN $1::bool THEN $2 ELSE name END,
    website = CASE WHEN $3::bool THEN $4 ELSE website END,
    aliases = CASE WHEN $5::bool THEN $6::text[] ELSE aliases END,
    category = CASE WHEN $7::bool THEN $8 ELSE category END,
    services = CASE WHEN $9::bool THEN $10::jsonb ELSE services END,
    location = CASE WHEN $11::bool THEN $12::jsonb ELSE location END
WHERE id = $13 AND tenant_id = $14 AND status = 'active'
RETURNING id, tenant_id, status, name, website, aliases, category, services, location, created_at, activated_at
`

type UpdateActiveBusinessProfileParams struct {
	NameSet     bool
	Name        string
	WebsiteSet  bool
	Website     *string
	AliasesSet  bool
	Aliases     []string
	CategorySet bool
	Category    *string
	ServicesSet bool
	Services    json.RawMessage
	LocationSet bool
	Location    json.RawMessage
	BusinessID  uuid.UUID
	TenantID    uuid.UUID
}

func (q *Queries) UpdateActiveBusinessProfile(ctx context.Context, arg UpdateActiveBusinessProfileParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateActiveBusinessProfile,
		arg.NameSet,
		arg.Name,
		arg.WebsiteSet,
		arg.Website,
		arg.AliasesSet,
		arg.Aliases,
		arg.CategorySet,
		arg.Category,
		arg.ServicesSet,
		arg.Services,
		arg.LocationSet,
		arg.Location,
		arg.BusinessID,
		arg.TenantID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.Name,
		&i.Website,
		&i.Aliases,
		&i.Category,
		&i.Services,
		&i.Location,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (
  tenant_id, plan_code, stripe_customer_id, stripe_subscription_id,
  stripe_status, past_due_since, comped, current_period_end, cancel_at_period_end
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (tenant_id) DO UPDATE SET
  plan_code=EXCLUDED.plan_code, stripe_customer_id=EXCLUDED.stripe_customer_id,
  stripe_subscription_id=EXCLUDED.stripe_subscription_id, stripe_status=EXCLUDED.stripe_status,
  past_due_since=EXCLUDED.past_due_since, comped=EXCLUDED.comped,
  current_period_end=EXCLUDED.current_period_end, cancel_at_period_end=EXCLUDED.cancel_at_period_end,
  updated_at=now()
`

type UpsertSubscriptionParams struct {
	TenantID             uuid.UUID
	PlanCode             string
	StripeCustomerID     *string
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
	Comped               bool
	CurrentPeriodEnd     *time.Time
	CancelAtPeriodEnd    bool
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.TenantID,
		arg.PlanCode,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StripeStatus,
		arg.PastDueSince,
		arg.Comped,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	return err
}
