// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: improve.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getFinding = `-- name: GetFinding :one
SELECT id, account_id, business_id, key, source, category, title, body, steps, detail, result_ids, prompt_ids, sources, blocking, reach, priority, status, dismissal_reason, first_seen_at, last_seen_at, completed_at, dismissed_at, verified_at FROM findings WHERE id = $1 AND account_id = $2
`

type GetFindingParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) GetFinding(ctx context.Context, arg GetFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, arg.ID, arg.AccountID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessID,
		&i.Key,
		&i.Source,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.Steps,
		&i.Detail,
		&i.ResultIds,
		&i.PromptIds,
		&i.Sources,
		&i.Blocking,
		&i.Reach,
		&i.Priority,
		&i.Status,
		&i.DismissalReason,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CompletedAt,
		&i.DismissedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getPublishedSiteAudit = `-- name: GetPublishedSiteAudit :one
SELECT id, account_id, business_id, monitoring_run_id, checked_at, pages_read, failure, checks, published FROM site_audits WHERE business_id = $1 AND account_id = $2 AND published
`

type GetPublishedSiteAuditParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) GetPublishedSiteAudit(ctx context.Context, arg GetPublishedSiteAuditParams) (SiteAudit, error) {
	row := q.db.QueryRow(ctx, getPublishedSiteAudit, arg.BusinessID, arg.AccountID)
	var i SiteAudit
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessID,
		&i.MonitoringRunID,
		&i.CheckedAt,
		&i.PagesRead,
		&i.Failure,
		&i.Checks,
		&i.Published,
	)
	return i, err
}

const insertSiteAudit = `-- name: InsertSiteAudit :one
INSERT INTO site_audits (id,account_id,business_id,monitoring_run_id,checked_at,pages_read,failure,checks,published)
SELECT $1,$2,$3,r.id,now(),$4,$5,$6,false
FROM monitoring_runs r JOIN businesses b ON b.id=r.business_id
WHERE r.id = $7 AND r.business_id = $3 AND b.account_id = $2
ON CONFLICT (monitoring_run_id) DO NOTHING
RETURNING id
`

type InsertSiteAuditParams struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	BusinessID      uuid.UUID
	PagesRead       int32
	Failure         *string
	Checks          json.RawMessage
	MonitoringRunID uuid.UUID
}

// The unique monitoring_run_id makes a retried publish a no-op rather than a
// second audit, which is the whole idempotency story now that there is no
// generation state machine.
// The run is joined rather than passed straight through, so the insert only
// happens for a run that really belongs to this business and account.
func (q *Queries) InsertSiteAudit(ctx context.Context, arg InsertSiteAuditParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSiteAudit,
		arg.ID,
		arg.AccountID,
		arg.BusinessID,
		arg.PagesRead,
		arg.Failure,
		arg.Checks,
		arg.MonitoringRunID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listFindings = `-- name: ListFindings :many
SELECT f.id, f.account_id, f.business_id, f.key, f.source, f.category, f.title, f.body, f.steps, f.detail, f.result_ids, f.prompt_ids, f.sources, f.blocking, f.reach, f.priority, f.status, f.dismissal_reason, f.first_seen_at, f.last_seen_at, f.completed_at, f.dismissed_at, f.verified_at FROM findings f
WHERE f.business_id = $1 AND f.account_id = $2
  AND (f.status <> 'OPEN' OR f.last_seen_at >= COALESCE(
    (SELECT a.checked_at FROM site_audits a WHERE a.business_id = $1 AND a.published), '-infinity'::timestamptz))
ORDER BY f.blocking DESC,
  COALESCE(array_position($3::text[], f.category), array_length($3::text[], 1) + 1),
  f.reach DESC, f.priority, f.key
`

type ListFindingsParams struct {
	BusinessID    uuid.UUID
	AccountID     uuid.UUID
	CategoryOrder []string
}

// Active work is what the current audit still reproduces, so a finding the
// evidence has moved past drops out of the queue without needing a retired
// state. Both timestamps are the publishing transaction's now(), so "seen by the
// current audit" is an exact comparison rather than a tolerance. The ordering is
// the product's triage: blockers, then the work most within the business's own
// control, then how many answers are affected.
//
// category_order is passed in rather than written here as a literal, because the
// sequence is catalog data owned by the visibility package; a copy in SQL would
// drift the first time a category is added. An unknown category sorts last.
func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings, arg.BusinessID, arg.AccountID, arg.CategoryOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BusinessID,
			&i.Key,
			&i.Source,
			&i.Category,
			&i.Title,
			&i.Body,
			&i.Steps,
			&i.Detail,
			&i.ResultIds,
			&i.PromptIds,
			&i.Sources,
			&i.Blocking,
			&i.Reach,
			&i.Priority,
			&i.Status,
			&i.DismissalReason,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CompletedAt,
			&i.DismissedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadMonitoringEvidence = `-- name: LoadMonitoringEvidence :many
SELECT r.id AS run_id,pr.id AS result_id,pr.prompt_id,p.text AS prompt,pr.response_text,
 EXISTS(SELECT 1 FROM mentions m WHERE m.prompt_result_id=pr.id AND m.subject='self') AS mentioned,
 COALESCE((SELECT json_agg(json_build_object(
    'url',c.url,'domain',c.domain,
    'competitors',COALESCE((SELECT array_agg(DISTINCT co.name ORDER BY co.name)
      FROM mention_citations mc JOIN mentions m ON m.id=mc.mention_id
      JOIN competitors co ON co.id=m.competitor_id WHERE mc.citation_id=c.id),'{}')
  ) ORDER BY c.cite_order) FROM citations c WHERE c.prompt_result_id=pr.id),'[]')::jsonb AS citations
FROM monitoring_runs r JOIN prompt_results pr ON pr.run_id=r.id JOIN prompts p ON p.id=pr.prompt_id JOIN businesses b ON b.id=r.business_id
WHERE r.business_id = $1 AND b.account_id = $2 AND r.analysis_completed_at IS NOT NULL
 AND r.id IN (SELECT id FROM monitoring_runs WHERE business_id = $1 AND analysis_completed_at IS NOT NULL ORDER BY scheduled_for DESC LIMIT 4)
 AND pr.status='succeeded' ORDER BY r.scheduled_for DESC,pr.requested_at,pr.id
`

type LoadMonitoringEvidenceParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type LoadMonitoringEvidenceRow struct {
	RunID        uuid.UUID
	ResultID     uuid.UUID
	PromptID     uuid.UUID
	Prompt       string
	ResponseText *string
	Mentioned    bool
	Citations    json.RawMessage
}

// Each citation carries the businesses the answer cited IT for, resolved through
// mention_citations (05). Grouping the competitors under their own citation
// rather than under the result is the whole point: every business named anywhere
// in an answer is a much larger set than the businesses a given source was cited
// for, and a finder that confuses the two recommends sources on invented
// evidence.
func (q *Queries) LoadMonitoringEvidence(ctx context.Context, arg LoadMonitoringEvidenceParams) ([]LoadMonitoringEvidenceRow, error) {
	rows, err := q.db.Query(ctx, loadMonitoringEvidence, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadMonitoringEvidenceRow
	for rows.Next() {
		var i LoadMonitoringEvidenceRow
		if err := rows.Scan(
			&i.RunID,
			&i.ResultID,
			&i.PromptID,
			&i.Prompt,
			&i.ResponseText,
			&i.Mentioned,
			&i.Citations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSiteAudit = `-- name: PublishSiteAudit :exec
UPDATE site_audits SET published = (id = $1) WHERE business_id = $2 AND (published OR id = $1)
`

type PublishSiteAuditParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

// Unpublish-then-publish under one transaction, guarded by the partial unique
// index, so exactly one audit is ever current for a business.
func (q *Queries) PublishSiteAudit(ctx context.Context, arg PublishSiteAuditParams) error {
	_, err := q.db.Exec(ctx, publishSiteAudit, arg.ID, arg.BusinessID)
	return err
}

const setFindingStatus = `-- name: SetFindingStatus :one
UPDATE findings SET
  status = $1,
  dismissal_reason = CASE WHEN $1 = 'DISMISSED' THEN $2 ELSE NULL END,
  completed_at = CASE WHEN $1 = 'DONE' THEN now() ELSE NULL END,
  dismissed_at = CASE WHEN $1 = 'DISMISSED' THEN now() ELSE NULL END,
  verified_at = NULL
WHERE id = $3 AND account_id = $4 AND status = $5
RETURNING id, account_id, business_id, key, source, category, title, body, steps, detail, result_ids, prompt_ids, sources, blocking, reach, priority, status, dismissal_reason, first_seen_at, last_seen_at, completed_at, dismissed_at, verified_at
`

type SetFindingStatusParams struct {
	Status          string
	DismissalReason *string
	ID              uuid.UUID
	AccountID       uuid.UUID
	PreviousStatus  string
}

func (q *Queries) SetFindingStatus(ctx context.Context, arg SetFindingStatusParams) (Finding, error) {
	row := q.db.QueryRow(ctx, setFindingStatus,
		arg.Status,
		arg.DismissalReason,
		arg.ID,
		arg.AccountID,
		arg.PreviousStatus,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessID,
		&i.Key,
		&i.Source,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.Steps,
		&i.Detail,
		&i.ResultIds,
		&i.PromptIds,
		&i.Sources,
		&i.Blocking,
		&i.Reach,
		&i.Priority,
		&i.Status,
		&i.DismissalReason,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CompletedAt,
		&i.DismissedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :exec
INSERT INTO findings (id,account_id,business_id,key,source,category,title,body,steps,detail,result_ids,prompt_ids,sources,blocking,reach,priority)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
ON CONFLICT (business_id,key) DO UPDATE SET
  source=EXCLUDED.source,category=EXCLUDED.category,title=EXCLUDED.title,body=EXCLUDED.body,steps=EXCLUDED.steps,detail=EXCLUDED.detail,
  result_ids=EXCLUDED.result_ids,prompt_ids=EXCLUDED.prompt_ids,sources=EXCLUDED.sources,
  blocking=EXCLUDED.blocking,reach=EXCLUDED.reach,priority=EXCLUDED.priority,
  last_seen_at=now(),
  status=CASE WHEN findings.status='DONE' THEN 'OPEN' ELSE findings.status END,
  completed_at=CASE WHEN findings.status='DONE' THEN NULL ELSE findings.completed_at END,
  verified_at=CASE WHEN findings.status='DONE' THEN NULL ELSE findings.verified_at END
`

type UpsertFindingParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	BusinessID uuid.UUID
	Key        string
	Source     string
	Category   string
	Title      string
	Body       string
	Steps      json.RawMessage
	Detail     string
	ResultIds  []uuid.UUID
	PromptIds  []uuid.UUID
	Sources    []string
	Blocking   bool
	Reach      int32
	Priority   int32
}

// A finder reproducing a key refreshes the evidence and moves last_seen_at
// forward without touching the user's own decision. A DONE finding that comes
// back reopens — that single rule is the entire regression story. A DISMISSED
// one stays dismissed, which is the entire suppression story.
func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) error {
	_, err := q.db.Exec(ctx, upsertFinding,
		arg.ID,
		arg.AccountID,
		arg.BusinessID,
		arg.Key,
		arg.Source,
		arg.Category,
		arg.Title,
		arg.Body,
		arg.Steps,
		arg.Detail,
		arg.ResultIds,
		arg.PromptIds,
		arg.Sources,
		arg.Blocking,
		arg.Reach,
		arg.Priority,
	)
	return err
}

const verifyCompletedFindings = `-- name: VerifyCompletedFindings :exec
UPDATE findings SET verified_at=now()
WHERE business_id = $1 AND account_id = $2
  AND status='DONE' AND verified_at IS NULL AND completed_at IS NOT NULL
  AND NOT (key = ANY($3::text[]))
`

type VerifyCompletedFindingsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
	SeenKeys   []string
}

// A completed finding the latest run did not reproduce is confirmed fixed. This
// re-checks the finding, never the visibility that followed it, so it carries no
// causal claim.
func (q *Queries) VerifyCompletedFindings(ctx context.Context, arg VerifyCompletedFindingsParams) error {
	_, err := q.db.Exec(ctx, verifyCompletedFindings, arg.BusinessID, arg.AccountID, arg.SeenKeys)
	return err
}
