// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const citationDomainStats = `-- name: CitationDomainStats :many
SELECT c.domain,coalesce(array_agg(DISTINCT ar.id),'{}')::uuid[] AS result_ids
FROM analyzed_results ar JOIN citations c ON c.prompt_result_id=ar.id
WHERE ar.business_id = $1 AND ar.account_id = $2
GROUP BY c.domain ORDER BY count(DISTINCT ar.id) DESC,c.domain
`

type CitationDomainStatsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type CitationDomainStatsRow struct {
	Domain    string
	ResultIds []uuid.UUID
}

func (q *Queries) CitationDomainStats(ctx context.Context, arg CitationDomainStatsParams) ([]CitationDomainStatsRow, error) {
	rows, err := q.db.Query(ctx, citationDomainStats, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CitationDomainStatsRow
	for rows.Next() {
		var i CitationDomainStatsRow
		if err := rows.Scan(&i.Domain, &i.ResultIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const citationSources = `-- name: CitationSources :many
SELECT c.domain,c.url,c.title,c.subject,ar.prompt_id,p.text AS prompt_text,ar.id AS result_id
FROM analyzed_results ar JOIN citations c ON c.prompt_result_id=ar.id
JOIN prompts p ON p.id=ar.prompt_id AND p.business_id=ar.business_id
WHERE ar.business_id = $1 AND ar.account_id = $2
ORDER BY c.domain,c.url,c.cite_order,p.text
`

type CitationSourcesParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type CitationSourcesRow struct {
	Domain     string
	Url        string
	Title      *string
	Subject    string
	PromptID   uuid.UUID
	PromptText string
	ResultID   uuid.UUID
}

func (q *Queries) CitationSources(ctx context.Context, arg CitationSourcesParams) ([]CitationSourcesRow, error) {
	rows, err := q.db.Query(ctx, citationSources, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CitationSourcesRow
	for rows.Next() {
		var i CitationSourcesRow
		if err := rows.Scan(
			&i.Domain,
			&i.Url,
			&i.Title,
			&i.Subject,
			&i.PromptID,
			&i.PromptText,
			&i.ResultID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const competitorOverall = `-- name: CompetitorOverall :many
SELECT co.id,co.name,co.status,co.aliases,co.suggested_aliases,
 count(DISTINCT am.result_id)::int AS mentioned,count(am.mention_id)::int AS total_mentions,
 coalesce(avg(am.mention_order),0)::float8 AS avg_order,
 coalesce(array_agg(DISTINCT am.result_id) FILTER (WHERE am.result_id IS NOT NULL),'{}')::uuid[] AS result_ids
FROM competitors co JOIN businesses owner ON owner.id=co.business_id
LEFT JOIN (
 SELECT m.competitor_id,m.id AS mention_id,m.mention_order,ar.id AS result_id
 FROM analyzed_results ar JOIN mentions m ON m.prompt_result_id=ar.id AND m.subject='competitor'
 WHERE ar.business_id = $1 AND ar.account_id = $2
) am ON am.competitor_id=co.id
WHERE co.business_id = $1 AND owner.account_id = $2
GROUP BY co.id,co.name,co.status,co.aliases,co.suggested_aliases
ORDER BY count(DISTINCT am.result_id) DESC,co.name
`

type CompetitorOverallParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type CompetitorOverallRow struct {
	ID               uuid.UUID
	Name             string
	Status           string
	Aliases          []string
	SuggestedAliases []string
	Mentioned        int32
	TotalMentions    int32
	AvgOrder         float64
	ResultIds        []uuid.UUID
}

func (q *Queries) CompetitorOverall(ctx context.Context, arg CompetitorOverallParams) ([]CompetitorOverallRow, error) {
	rows, err := q.db.Query(ctx, competitorOverall, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitorOverallRow
	for rows.Next() {
		var i CompetitorOverallRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Aliases,
			&i.SuggestedAliases,
			&i.Mentioned,
			&i.TotalMentions,
			&i.AvgOrder,
			&i.ResultIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const competitorPerPrompt = `-- name: CompetitorPerPrompt :many
SELECT m.competitor_id,ar.prompt_id,p.text AS prompt_text,
 coalesce(array_agg(DISTINCT ar.id),'{}')::uuid[] AS result_ids
FROM analyzed_results ar JOIN mentions m ON m.prompt_result_id=ar.id AND m.subject='competitor'
JOIN prompts p ON p.id=ar.prompt_id
WHERE ar.business_id = $1 AND ar.account_id = $2
GROUP BY m.competitor_id,ar.prompt_id,p.text ORDER BY count(DISTINCT ar.id) DESC,p.text
`

type CompetitorPerPromptParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type CompetitorPerPromptRow struct {
	CompetitorID *uuid.UUID
	PromptID     uuid.UUID
	PromptText   string
	ResultIds    []uuid.UUID
}

func (q *Queries) CompetitorPerPrompt(ctx context.Context, arg CompetitorPerPromptParams) ([]CompetitorPerPromptRow, error) {
	rows, err := q.db.Query(ctx, competitorPerPrompt, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitorPerPromptRow
	for rows.Next() {
		var i CompetitorPerPromptRow
		if err := rows.Scan(
			&i.CompetitorID,
			&i.PromptID,
			&i.PromptText,
			&i.ResultIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const competitorTrend = `-- name: CompetitorTrend :many
SELECT m.competitor_id,ar.run_id,ar.scheduled_for,count(DISTINCT ar.id)::int AS mentioned,
 coalesce(array_agg(DISTINCT ar.id),'{}')::uuid[] AS result_ids
FROM analyzed_results ar JOIN mentions m ON m.prompt_result_id=ar.id AND m.subject='competitor'
WHERE ar.business_id = $1 AND ar.account_id = $2
GROUP BY m.competitor_id,ar.run_id,ar.scheduled_for ORDER BY ar.scheduled_for
`

type CompetitorTrendParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type CompetitorTrendRow struct {
	CompetitorID *uuid.UUID
	RunID        uuid.UUID
	ScheduledFor time.Time
	Mentioned    int32
	ResultIds    []uuid.UUID
}

func (q *Queries) CompetitorTrend(ctx context.Context, arg CompetitorTrendParams) ([]CompetitorTrendRow, error) {
	rows, err := q.db.Query(ctx, competitorTrend, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitorTrendRow
	for rows.Next() {
		var i CompetitorTrendRow
		if err := rows.Scan(
			&i.CompetitorID,
			&i.RunID,
			&i.ScheduledFor,
			&i.Mentioned,
			&i.ResultIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const keywordStats = `-- name: KeywordStats :many
SELECT kw::text AS keyword,coalesce(array_agg(DISTINCT id),'{}')::uuid[] AS result_ids
FROM analyzed_results CROSS JOIN LATERAL unnest(keywords) AS kw
WHERE business_id = $1 AND account_id = $2
GROUP BY kw ORDER BY count(DISTINCT id) DESC,kw
`

type KeywordStatsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type KeywordStatsRow struct {
	Keyword   string
	ResultIds []uuid.UUID
}

func (q *Queries) KeywordStats(ctx context.Context, arg KeywordStatsParams) ([]KeywordStatsRow, error) {
	rows, err := q.db.Query(ctx, keywordStats, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeywordStatsRow
	for rows.Next() {
		var i KeywordStatsRow
		if err := rows.Scan(&i.Keyword, &i.ResultIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promptChanges = `-- name: PromptChanges :many
SELECT d,sum(added)::int AS added,sum(retired)::int AS retired,sum(replaced)::int AS replaced
FROM (
 SELECT date_trunc('day',p.created_at)::timestamptz AS d,
 CASE WHEN p.replaces_prompt_id IS NULL THEN 1 ELSE 0 END AS added,0 AS retired,
 CASE WHEN p.replaces_prompt_id IS NOT NULL THEN 1 ELSE 0 END AS replaced
 FROM prompts p JOIN businesses b ON b.id=p.business_id
 WHERE b.id = $1 AND b.account_id = $2
 UNION ALL
 SELECT date_trunc('day',p.retired_at)::timestamptz AS d,0,1,0
 FROM prompts p JOIN businesses b ON b.id=p.business_id
 WHERE b.id = $1 AND b.account_id = $2 AND p.retired_at IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM prompts r WHERE r.replaces_prompt_id=p.id
  AND date_trunc('day',r.created_at)=date_trunc('day',p.retired_at))
) e GROUP BY d ORDER BY d
`

type PromptChangesParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type PromptChangesRow struct {
	D        time.Time
	Added    int32
	Retired  int32
	Replaced int32
}

func (q *Queries) PromptChanges(ctx context.Context, arg PromptChangesParams) ([]PromptChangesRow, error) {
	rows, err := q.db.Query(ctx, promptChanges, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptChangesRow
	for rows.Next() {
		var i PromptChangesRow
		if err := rows.Scan(
			&i.D,
			&i.Added,
			&i.Retired,
			&i.Replaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promptLatestStats = `-- name: PromptLatestStats :many
SELECT DISTINCT ON (ar.prompt_id) ar.prompt_id,ar.id AS result_id,ar.sentiment,
 coalesce(sm.mention_order,0)::int4 AS mention_order,(sm.prompt_result_id IS NOT NULL)::bool AS mentioned
FROM analyzed_results ar JOIN prompts p ON p.id=ar.prompt_id
LEFT JOIN (
 SELECT DISTINCT ON (prompt_result_id) prompt_result_id,mention_order FROM mentions
 WHERE subject='self' ORDER BY prompt_result_id,mention_order
) sm ON sm.prompt_result_id=ar.id
WHERE ar.business_id = $1 AND ar.account_id = $2 AND p.status='active'
ORDER BY ar.prompt_id,ar.requested_at DESC,ar.id DESC
`

type PromptLatestStatsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type PromptLatestStatsRow struct {
	PromptID     uuid.UUID
	ResultID     uuid.UUID
	Sentiment    *string
	MentionOrder int32
	Mentioned    bool
}

func (q *Queries) PromptLatestStats(ctx context.Context, arg PromptLatestStatsParams) ([]PromptLatestStatsRow, error) {
	rows, err := q.db.Query(ctx, promptLatestStats, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptLatestStatsRow
	for rows.Next() {
		var i PromptLatestStatsRow
		if err := rows.Scan(
			&i.PromptID,
			&i.ResultID,
			&i.Sentiment,
			&i.MentionOrder,
			&i.Mentioned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promptTrends = `-- name: PromptTrends :many
SELECT ar.prompt_id,ar.run_id,ar.scheduled_for,ar.id AS result_id,ar.has_self_mention AS mentioned
FROM analyzed_results ar WHERE ar.business_id = $1 AND ar.account_id = $2
ORDER BY ar.prompt_id,ar.scheduled_for,ar.id
`

type PromptTrendsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type PromptTrendsRow struct {
	PromptID     uuid.UUID
	RunID        uuid.UUID
	ScheduledFor time.Time
	ResultID     uuid.UUID
	Mentioned    bool
}

func (q *Queries) PromptTrends(ctx context.Context, arg PromptTrendsParams) ([]PromptTrendsRow, error) {
	rows, err := q.db.Query(ctx, promptTrends, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTrendsRow
	for rows.Next() {
		var i PromptTrendsRow
		if err := rows.Scan(
			&i.PromptID,
			&i.RunID,
			&i.ScheduledFor,
			&i.ResultID,
			&i.Mentioned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sentimentStats = `-- name: SentimentStats :many
SELECT sentiment,coalesce(array_agg(id ORDER BY id),'{}')::uuid[] AS result_ids
FROM analyzed_results WHERE business_id = $1 AND account_id = $2 AND sentiment IS NOT NULL
GROUP BY sentiment ORDER BY count(*) DESC,sentiment
`

type SentimentStatsParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type SentimentStatsRow struct {
	Sentiment *string
	ResultIds []uuid.UUID
}

func (q *Queries) SentimentStats(ctx context.Context, arg SentimentStatsParams) ([]SentimentStatsRow, error) {
	rows, err := q.db.Query(ctx, sentimentStats, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SentimentStatsRow
	for rows.Next() {
		var i SentimentStatsRow
		if err := rows.Scan(&i.Sentiment, &i.ResultIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibilityTrend = `-- name: VisibilityTrend :many
SELECT run_id,scheduled_for,count(*)::int AS analyzed,
 count(*) FILTER (WHERE has_self_mention)::int AS mentioned,
 coalesce(array_agg(id ORDER BY id),'{}')::uuid[] AS result_ids
FROM analyzed_results WHERE business_id = $1 AND account_id = $2
GROUP BY run_id,scheduled_for ORDER BY scheduled_for
`

type VisibilityTrendParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type VisibilityTrendRow struct {
	RunID        uuid.UUID
	ScheduledFor time.Time
	Analyzed     int32
	Mentioned    int32
	ResultIds    []uuid.UUID
}

func (q *Queries) VisibilityTrend(ctx context.Context, arg VisibilityTrendParams) ([]VisibilityTrendRow, error) {
	rows, err := q.db.Query(ctx, visibilityTrend, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibilityTrendRow
	for rows.Next() {
		var i VisibilityTrendRow
		if err := rows.Scan(
			&i.RunID,
			&i.ScheduledFor,
			&i.Analyzed,
			&i.Mentioned,
			&i.ResultIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
