// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	Slug      string
}

type AccountMembership struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type AnalyzedResult struct {
	ID             uuid.UUID
	RunID          uuid.UUID
	PromptID       uuid.UUID
	Status         string
	Model          *string
	Request        json.RawMessage
	RawResponse    *json.RawMessage
	ResponseText   *string
	Error          *string
	RequestedAt    time.Time
	CompletedAt    time.Time
	ScheduledFor   time.Time
	BusinessID     uuid.UUID
	AccountID      uuid.UUID
	Sentiment      *string
	Keywords       []string
	HasSelfMention bool
}

type Business struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Status      string
	Name        string
	Website     *string
	Aliases     []string
	Category    *string
	Services    json.RawMessage
	Location    *json.RawMessage
	CreatedAt   time.Time
	ActivatedAt *time.Time
}

type Citation struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Url            string
	Domain         string
	Title          *string
	CiteOrder      int32
	Subject        string
}

type Competitor struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Name             string
	Website          *string
	Aliases          []string
	SuggestedAliases []string
	Source           string
	Status           string
	CreatedAt        time.Time
}

type Mention struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Subject        string
	CompetitorID   *uuid.UUID
	MatchedBy      string
	MentionOrder   int32
	Excerpt        string
	VerbatimName   *string
}

type MonitoringRun struct {
	ID                  uuid.UUID
	BusinessID          uuid.UUID
	Platform            string
	Trigger             string
	ScheduledFor        time.Time
	Status              string
	WorkflowID          string
	StartedAt           time.Time
	CompletedAt         *time.Time
	AnalysisCompletedAt *time.Time
	ExpectedResults     *int32
}

type ProfileProposal struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	Payload    json.RawMessage
	Status     string
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

type Prompt struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	Text             string
	Status           string
	ReplacesPromptID *uuid.UUID
	CreatedAt        time.Time
	RetiredAt        *time.Time
}

type PromptResult struct {
	ID           uuid.UUID
	RunID        uuid.UUID
	PromptID     uuid.UUID
	Status       string
	Model        *string
	Request      json.RawMessage
	RawResponse  *json.RawMessage
	ResponseText *string
	Error        *string
	RequestedAt  time.Time
	CompletedAt  time.Time
}

type ResultAnalysis struct {
	PromptResultID    uuid.UUID
	Sentiment         *string
	Keywords          []string
	Excerpts          json.RawMessage
	AnalysisModel     string
	ExtractionVersion int32
	AnalyzedAt        time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Subscription struct {
	AccountID            uuid.UUID
	PlanCode             string
	StripeCustomerID     *string
	StripeSubscriptionID *string
	StripeStatus         *string
	PastDueSince         *time.Time
	Comped               bool
	CurrentPeriodEnd     *time.Time
	CancelAtPeriodEnd    bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	GoogleSub *string
}
