// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opportunities.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const finishAssessmentGeneration = `-- name: FinishAssessmentGeneration :exec
UPDATE assessment_generations SET status = $1, error = $2, completed_at = now()
WHERE id = $3 AND account_id = $4
`

type FinishAssessmentGenerationParams struct {
	Status    string
	Error     *string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) FinishAssessmentGeneration(ctx context.Context, arg FinishAssessmentGenerationParams) error {
	_, err := q.db.Exec(ctx, finishAssessmentGeneration,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.AccountID,
	)
	return err
}

const getCurrentOpportunity = `-- name: GetCurrentOpportunity :one
SELECT o.id,o.business_id,o.practice_key,o.subject_key,o.rank,o.presentation,o.user_status,o.dismissal_reason,
 o.completion_baseline,o.first_seen_at,o.updated_at,(o.current_generation_id IS NOT NULL)::bool AS current,
 COALESCE(f.focus,false)::bool AS focus,a.status AS assessment_status,
 a.result_ids,a.prompt_ids,a.checked_sources,a.explanation,a.assessed_at
FROM opportunities o JOIN visibility_assessments a ON a.id=o.current_assessment_id
 LEFT JOIN opportunity_focus f ON f.id=o.id
WHERE o.id = $1 AND o.account_id = $2
`

type GetCurrentOpportunityParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetCurrentOpportunityRow struct {
	ID                 uuid.UUID
	BusinessID         uuid.UUID
	PracticeKey        string
	SubjectKey         string
	Rank               int32
	Presentation       json.RawMessage
	UserStatus         string
	DismissalReason    *string
	CompletionBaseline *json.RawMessage
	FirstSeenAt        time.Time
	UpdatedAt          time.Time
	Current            bool
	Focus              bool
	AssessmentStatus   string
	ResultIds          []uuid.UUID
	PromptIds          []uuid.UUID
	CheckedSources     []string
	Explanation        string
	AssessedAt         time.Time
}

func (q *Queries) GetCurrentOpportunity(ctx context.Context, arg GetCurrentOpportunityParams) (GetCurrentOpportunityRow, error) {
	row := q.db.QueryRow(ctx, getCurrentOpportunity, arg.ID, arg.AccountID)
	var i GetCurrentOpportunityRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PracticeKey,
		&i.SubjectKey,
		&i.Rank,
		&i.Presentation,
		&i.UserStatus,
		&i.DismissalReason,
		&i.CompletionBaseline,
		&i.FirstSeenAt,
		&i.UpdatedAt,
		&i.Current,
		&i.Focus,
		&i.AssessmentStatus,
		&i.ResultIds,
		&i.PromptIds,
		&i.CheckedSources,
		&i.Explanation,
		&i.AssessedAt,
	)
	return i, err
}

const insertOpportunityEvent = `-- name: InsertOpportunityEvent :exec
INSERT INTO opportunity_events (id,opportunity_id,account_id,event_key,event_type,payload)
SELECT $1,$2,$3,$4,$5,$6
WHERE EXISTS (SELECT 1 FROM opportunities WHERE id = $2 AND account_id = $3)
ON CONFLICT (opportunity_id,event_key) DO NOTHING
`

type InsertOpportunityEventParams struct {
	ID            uuid.UUID
	OpportunityID uuid.UUID
	AccountID     uuid.UUID
	EventKey      string
	EventType     string
	Payload       json.RawMessage
}

func (q *Queries) InsertOpportunityEvent(ctx context.Context, arg InsertOpportunityEventParams) error {
	_, err := q.db.Exec(ctx, insertOpportunityEvent,
		arg.ID,
		arg.OpportunityID,
		arg.AccountID,
		arg.EventKey,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listCompletedGenerationOpportunities = `-- name: ListCompletedGenerationOpportunities :many
SELECT o.id,o.practice_key,o.subject_key,a.status AS assessment_status,a.result_ids,a.prompt_ids
FROM opportunities o JOIN visibility_assessments a
 ON a.business_id=o.business_id AND a.practice_key=o.practice_key AND a.subject_key=o.subject_key
WHERE o.account_id = $1 AND o.business_id = $2 AND o.user_status='COMPLETED'
 AND a.generation_id = $3 ORDER BY o.id
`

type ListCompletedGenerationOpportunitiesParams struct {
	AccountID    uuid.UUID
	BusinessID   uuid.UUID
	GenerationID uuid.UUID
}

type ListCompletedGenerationOpportunitiesRow struct {
	ID               uuid.UUID
	PracticeKey      string
	SubjectKey       string
	AssessmentStatus string
	ResultIds        []uuid.UUID
	PromptIds        []uuid.UUID
}

// Outcome observations match this generation's assessment by practice identity,
// not by the opportunity's current assessment pointer, so a completed item that
// has since turned MET still receives its later observation.
func (q *Queries) ListCompletedGenerationOpportunities(ctx context.Context, arg ListCompletedGenerationOpportunitiesParams) ([]ListCompletedGenerationOpportunitiesRow, error) {
	rows, err := q.db.Query(ctx, listCompletedGenerationOpportunities, arg.AccountID, arg.BusinessID, arg.GenerationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedGenerationOpportunitiesRow
	for rows.Next() {
		var i ListCompletedGenerationOpportunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.PracticeKey,
			&i.SubjectKey,
			&i.AssessmentStatus,
			&i.ResultIds,
			&i.PromptIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentOpportunities = `-- name: ListCurrentOpportunities :many
SELECT o.id,o.practice_key,o.subject_key,o.rank,o.presentation,o.user_status,o.dismissal_reason,
 o.completion_baseline,o.first_seen_at,o.updated_at,(o.current_generation_id IS NOT NULL)::bool AS current,
 COALESCE(f.focus,false)::bool AS focus,a.status AS assessment_status,
 a.result_ids,a.prompt_ids,a.checked_sources,a.explanation,a.assessed_at
FROM opportunities o JOIN visibility_assessments a ON a.id=o.current_assessment_id
 LEFT JOIN opportunity_focus f ON f.id=o.id
WHERE o.business_id = $1 AND o.account_id = $2
 AND (o.current_generation_id IS NOT NULL OR o.user_status <> 'OPEN')
ORDER BY o.rank,o.practice_key,o.subject_key
`

type ListCurrentOpportunitiesParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type ListCurrentOpportunitiesRow struct {
	ID                 uuid.UUID
	PracticeKey        string
	SubjectKey         string
	Rank               int32
	Presentation       json.RawMessage
	UserStatus         string
	DismissalReason    *string
	CompletionBaseline *json.RawMessage
	FirstSeenAt        time.Time
	UpdatedAt          time.Time
	Current            bool
	Focus              bool
	AssessmentStatus   string
	ResultIds          []uuid.UUID
	PromptIds          []uuid.UUID
	CheckedSources     []string
	Explanation        string
	AssessedAt         time.Time
}

// A row that stopped being current and that the user never acted on is not
// history — it simply disappears.
func (q *Queries) ListCurrentOpportunities(ctx context.Context, arg ListCurrentOpportunitiesParams) ([]ListCurrentOpportunitiesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentOpportunities, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentOpportunitiesRow
	for rows.Next() {
		var i ListCurrentOpportunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.PracticeKey,
			&i.SubjectKey,
			&i.Rank,
			&i.Presentation,
			&i.UserStatus,
			&i.DismissalReason,
			&i.CompletionBaseline,
			&i.FirstSeenAt,
			&i.UpdatedAt,
			&i.Current,
			&i.Focus,
			&i.AssessmentStatus,
			&i.ResultIds,
			&i.PromptIds,
			&i.CheckedSources,
			&i.Explanation,
			&i.AssessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunityOutcomeEvents = `-- name: ListOpportunityOutcomeEvents :many
SELECT payload,created_at FROM opportunity_events
WHERE opportunity_id = $1 AND account_id = $2 AND event_type='OUTCOME_OBSERVED'
ORDER BY created_at,event_key
`

type ListOpportunityOutcomeEventsParams struct {
	OpportunityID uuid.UUID
	AccountID     uuid.UUID
}

type ListOpportunityOutcomeEventsRow struct {
	Payload   json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) ListOpportunityOutcomeEvents(ctx context.Context, arg ListOpportunityOutcomeEventsParams) ([]ListOpportunityOutcomeEventsRow, error) {
	rows, err := q.db.Query(ctx, listOpportunityOutcomeEvents, arg.OpportunityID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpportunityOutcomeEventsRow
	for rows.Next() {
		var i ListOpportunityOutcomeEventsRow
		if err := rows.Scan(&i.Payload, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadMonitoringEvidence = `-- name: LoadMonitoringEvidence :many
SELECT r.id AS run_id,pr.id AS result_id,pr.prompt_id,p.text AS prompt,pr.response_text,
 EXISTS(SELECT 1 FROM mentions m WHERE m.prompt_result_id=pr.id AND m.subject='self') AS mentioned,
 COALESCE((SELECT array_agg(DISTINCT c.domain ORDER BY c.domain) FROM citations c WHERE c.prompt_result_id=pr.id),'{}')::text[] AS citation_domains,
 COALESCE((SELECT array_agg(c.url ORDER BY c.cite_order,c.id) FROM citations c WHERE c.prompt_result_id=pr.id),'{}')::text[] AS citation_urls,
 COALESCE((SELECT array_agg(DISTINCT co.name ORDER BY co.name) FROM mentions m JOIN competitors co ON co.id=m.competitor_id WHERE m.prompt_result_id=pr.id),'{}')::text[] AS competitors
FROM monitoring_runs r JOIN prompt_results pr ON pr.run_id=r.id JOIN prompts p ON p.id=pr.prompt_id
JOIN businesses b ON b.id=r.business_id
WHERE r.business_id = $1 AND b.account_id = $2 AND r.analysis_completed_at IS NOT NULL
 AND r.id IN (SELECT id FROM monitoring_runs WHERE business_id = $1 AND analysis_completed_at IS NOT NULL ORDER BY scheduled_for DESC LIMIT 4)
 AND pr.status='succeeded' ORDER BY r.scheduled_for DESC,pr.requested_at,pr.id
`

type LoadMonitoringEvidenceParams struct {
	BusinessID uuid.UUID
	AccountID  uuid.UUID
}

type LoadMonitoringEvidenceRow struct {
	RunID           uuid.UUID
	ResultID        uuid.UUID
	PromptID        uuid.UUID
	Prompt          string
	ResponseText    *string
	Mentioned       bool
	CitationDomains []string
	CitationUrls    []string
	Competitors     []string
}

func (q *Queries) LoadMonitoringEvidence(ctx context.Context, arg LoadMonitoringEvidenceParams) ([]LoadMonitoringEvidenceRow, error) {
	rows, err := q.db.Query(ctx, loadMonitoringEvidence, arg.BusinessID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadMonitoringEvidenceRow
	for rows.Next() {
		var i LoadMonitoringEvidenceRow
		if err := rows.Scan(
			&i.RunID,
			&i.ResultID,
			&i.PromptID,
			&i.Prompt,
			&i.ResponseText,
			&i.Mentioned,
			&i.CitationDomains,
			&i.CitationUrls,
			&i.Competitors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOpportunityStatus = `-- name: SetOpportunityStatus :one
UPDATE opportunities SET user_status = $1, dismissal_reason = $2,
 completion_baseline = CASE WHEN $1 = 'COMPLETED' THEN COALESCE(completion_baseline, $3) ELSE completion_baseline END,
 updated_at = now() WHERE id = $4 AND account_id = $5
RETURNING business_id,practice_key,subject_key
`

type SetOpportunityStatusParams struct {
	UserStatus         string
	DismissalReason    *string
	CompletionBaseline *json.RawMessage
	ID                 uuid.UUID
	AccountID          uuid.UUID
}

type SetOpportunityStatusRow struct {
	BusinessID  uuid.UUID
	PracticeKey string
	SubjectKey  string
}

func (q *Queries) SetOpportunityStatus(ctx context.Context, arg SetOpportunityStatusParams) (SetOpportunityStatusRow, error) {
	row := q.db.QueryRow(ctx, setOpportunityStatus,
		arg.UserStatus,
		arg.DismissalReason,
		arg.CompletionBaseline,
		arg.ID,
		arg.AccountID,
	)
	var i SetOpportunityStatusRow
	err := row.Scan(&i.BusinessID, &i.PracticeKey, &i.SubjectKey)
	return i, err
}

const sweepStaleOpportunities = `-- name: SweepStaleOpportunities :exec
UPDATE opportunities SET current_generation_id = NULL, updated_at = now()
WHERE business_id = $1 AND account_id = $2
 AND current_generation_id IS NOT NULL AND current_generation_id <> $3::uuid
`

type SweepStaleOpportunitiesParams struct {
	BusinessID          uuid.UUID
	AccountID           uuid.UUID
	CurrentGenerationID uuid.UUID
}

// Everything the compiler did not produce this generation stops being current.
// The last-known presentation stays on the row so acted-on history still renders.
func (q *Queries) SweepStaleOpportunities(ctx context.Context, arg SweepStaleOpportunitiesParams) error {
	_, err := q.db.Exec(ctx, sweepStaleOpportunities, arg.BusinessID, arg.AccountID, arg.CurrentGenerationID)
	return err
}

const upsertAssessmentGeneration = `-- name: UpsertAssessmentGeneration :one
INSERT INTO assessment_generations (id,account_id,business_id,monitoring_run_id,status,compiler_version,ranker_version,module_plan)
SELECT $1,$2,$3,$4,'RUNNING',$5,$6,$7
WHERE EXISTS (SELECT 1 FROM monitoring_runs r JOIN businesses b ON b.id=r.business_id
 WHERE r.id = $4 AND r.business_id = $3 AND b.account_id = $2 AND r.analysis_completed_at IS NOT NULL)
ON CONFLICT (monitoring_run_id) DO UPDATE SET module_plan=assessment_generations.module_plan
RETURNING id,status
`

type UpsertAssessmentGenerationParams struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	BusinessID      uuid.UUID
	MonitoringRunID uuid.UUID
	CompilerVersion int32
	RankerVersion   int32
	ModulePlan      json.RawMessage
}

type UpsertAssessmentGenerationRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpsertAssessmentGeneration(ctx context.Context, arg UpsertAssessmentGenerationParams) (UpsertAssessmentGenerationRow, error) {
	row := q.db.QueryRow(ctx, upsertAssessmentGeneration,
		arg.ID,
		arg.AccountID,
		arg.BusinessID,
		arg.MonitoringRunID,
		arg.CompilerVersion,
		arg.RankerVersion,
		arg.ModulePlan,
	)
	var i UpsertAssessmentGenerationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const upsertEvidenceArtifact = `-- name: UpsertEvidenceArtifact :exec
INSERT INTO evidence_artifacts (id,generation_id,account_id,collector_key,collector_version,payload_version,status,checked_at,payload,error)
SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
WHERE EXISTS (SELECT 1 FROM assessment_generations WHERE id = $2 AND account_id = $3)
ON CONFLICT (generation_id,collector_key) DO UPDATE SET collector_version=EXCLUDED.collector_version,
 payload_version=EXCLUDED.payload_version,status=EXCLUDED.status,checked_at=EXCLUDED.checked_at,payload=EXCLUDED.payload,error=EXCLUDED.error
`

type UpsertEvidenceArtifactParams struct {
	ID               uuid.UUID
	GenerationID     uuid.UUID
	AccountID        uuid.UUID
	CollectorKey     string
	CollectorVersion int32
	PayloadVersion   int32
	Status           string
	CheckedAt        time.Time
	Payload          json.RawMessage
	Error            *string
}

func (q *Queries) UpsertEvidenceArtifact(ctx context.Context, arg UpsertEvidenceArtifactParams) error {
	_, err := q.db.Exec(ctx, upsertEvidenceArtifact,
		arg.ID,
		arg.GenerationID,
		arg.AccountID,
		arg.CollectorKey,
		arg.CollectorVersion,
		arg.PayloadVersion,
		arg.Status,
		arg.CheckedAt,
		arg.Payload,
		arg.Error,
	)
	return err
}

const upsertOpportunity = `-- name: UpsertOpportunity :one
INSERT INTO opportunities (id,account_id,business_id,practice_key,subject_key,current_assessment_id,current_generation_id,rank,presentation)
SELECT $1,$2,$3,$4,$5,$6,$7::uuid,$8,$9
WHERE EXISTS (SELECT 1 FROM visibility_assessments WHERE id = $6 AND account_id = $2 AND business_id = $3)
ON CONFLICT (business_id,practice_key,subject_key) DO UPDATE SET current_assessment_id=EXCLUDED.current_assessment_id,
 current_generation_id=EXCLUDED.current_generation_id,rank=EXCLUDED.rank,presentation=EXCLUDED.presentation,updated_at=now()
RETURNING id
`

type UpsertOpportunityParams struct {
	ID                  uuid.UUID
	AccountID           uuid.UUID
	BusinessID          uuid.UUID
	PracticeKey         string
	SubjectKey          string
	CurrentAssessmentID uuid.UUID
	CurrentGenerationID uuid.UUID
	Rank                int32
	Presentation        json.RawMessage
}

func (q *Queries) UpsertOpportunity(ctx context.Context, arg UpsertOpportunityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOpportunity,
		arg.ID,
		arg.AccountID,
		arg.BusinessID,
		arg.PracticeKey,
		arg.SubjectKey,
		arg.CurrentAssessmentID,
		arg.CurrentGenerationID,
		arg.Rank,
		arg.Presentation,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertVisibilityAssessment = `-- name: UpsertVisibilityAssessment :one
INSERT INTO visibility_assessments (id,generation_id,account_id,business_id,practice_key,criteria_version,
 assessor_key,assessor_version,subject_key,status,result_ids,prompt_ids,checked_sources,
 explanation,reach,persistence,evidence_quality,actionability,effort,payload_version,payload)
SELECT $1,$2,$3,$4,$5,$6,$7,
 $8,$9,$10,$11,$12,$13,
 $14,$15,$16,$17,$18,$19,$20,$21
WHERE EXISTS (SELECT 1 FROM assessment_generations WHERE id = $2 AND account_id = $3 AND business_id = $4)
ON CONFLICT (generation_id,practice_key,subject_key) DO UPDATE SET status=EXCLUDED.status,
 result_ids=EXCLUDED.result_ids,prompt_ids=EXCLUDED.prompt_ids,checked_sources=EXCLUDED.checked_sources,
 explanation=EXCLUDED.explanation,reach=EXCLUDED.reach,
 persistence=EXCLUDED.persistence,evidence_quality=EXCLUDED.evidence_quality,actionability=EXCLUDED.actionability,
 effort=EXCLUDED.effort,payload=EXCLUDED.payload
RETURNING id
`

type UpsertVisibilityAssessmentParams struct {
	ID              uuid.UUID
	GenerationID    uuid.UUID
	AccountID       uuid.UUID
	BusinessID      uuid.UUID
	PracticeKey     string
	CriteriaVersion int32
	AssessorKey     string
	AssessorVersion int32
	SubjectKey      string
	Status          string
	ResultIds       []uuid.UUID
	PromptIds       []uuid.UUID
	CheckedSources  []string
	Explanation     string
	Reach           int32
	Persistence     int32
	EvidenceQuality int32
	Actionability   int32
	Effort          int32
	PayloadVersion  int32
	Payload         json.RawMessage
}

func (q *Queries) UpsertVisibilityAssessment(ctx context.Context, arg UpsertVisibilityAssessmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertVisibilityAssessment,
		arg.ID,
		arg.GenerationID,
		arg.AccountID,
		arg.BusinessID,
		arg.PracticeKey,
		arg.CriteriaVersion,
		arg.AssessorKey,
		arg.AssessorVersion,
		arg.SubjectKey,
		arg.Status,
		arg.ResultIds,
		arg.PromptIds,
		arg.CheckedSources,
		arg.Explanation,
		arg.Reach,
		arg.Persistence,
		arg.EvidenceQuality,
		arg.Actionability,
		arg.Effort,
		arg.PayloadVersion,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
