package metrics

import (
	"errors"

	"opensight/internal/store/sqlc"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Metrics computes the shared product metrics over the design-02 tables.
type Metrics struct {
	q *sqlc.Queries
}

// New returns a Metrics backed by pool. Queries live in
// internal/store/queries/metrics.sql, generated by sqlc (sqlc.yaml) into
// internal/store/sqlc; the "an analyzed result" gate every metric shares is
// the analyzed_results view (internal/store/migrations/00012), not a
// duplicated predicate per query.
func New(pool *pgxpool.Pool) *Metrics {
	return &Metrics{q: sqlc.New(pool)}
}

func (m *Metrics) ready() error {
	if m == nil || m.q == nil {
		return errors.New("metrics database is required")
	}
	return nil
}

// percent returns num/denom as a percentage, guarding a zero denominator.
func percent(num, denom int) float64 {
	if denom == 0 {
		return 0
	}
	return float64(num) / float64(denom) * 100
}

// derefString reads a nullable text column the query's own WHERE already
// excludes (e.g. SentimentStats' "sentiment IS NOT NULL") — sqlc still types
// it as *string since it doesn't narrow nullability from a WHERE clause.
// Defensively returns "" rather than trust that exclusion blindly.
func derefString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
