// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration.sql

package testsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const TestQuery001 = `-- name: TestQuery001 :exec
DELETE FROM businesses WHERE tenant_id = $1
`

func (q *Queries) TestQuery001(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery001, tenantID)
	return err
}

const TestQuery002 = `-- name: TestQuery002 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery002(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery002, tenantID)
	return err
}

const TestQuery003 = `-- name: TestQuery003 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery003(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery003, id)
	return err
}

const TestQuery004 = `-- name: TestQuery004 :exec
INSERT INTO tenants (id, name) VALUES ($1, 'Out Of Order Tenant')
`

func (q *Queries) TestQuery004(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery004, id)
	return err
}

const TestQuery005 = `-- name: TestQuery005 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery005(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery005, id)
	return err
}

const TestQuery006 = `-- name: TestQuery006 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery006(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery006, id)
	return err
}

const TestQuery007 = `-- name: TestQuery007 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery007(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery007, tenantID)
	return err
}

const TestQuery008 = `-- name: TestQuery008 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery008(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery008, id)
	return err
}

const TestQuery009 = `-- name: TestQuery009 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Atlas Clinic')
`

type TestQuery009Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery009(ctx context.Context, arg TestQuery009Params) error {
	_, err := q.db.Exec(ctx, TestQuery009, arg.ID, arg.TenantID)
	return err
}

const TestQuery010 = `-- name: TestQuery010 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Other Clinic')
`

type TestQuery010Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery010(ctx context.Context, arg TestQuery010Params) error {
	_, err := q.db.Exec(ctx, TestQuery010, arg.ID, arg.TenantID)
	return err
}

const TestQuery011 = `-- name: TestQuery011 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'root canal clinic', 'active')
`

type TestQuery011Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery011(ctx context.Context, arg TestQuery011Params) error {
	_, err := q.db.Exec(ctx, TestQuery011, arg.ID, arg.BusinessID)
	return err
}

const TestQuery012 = `-- name: TestQuery012 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best specialist near me', 'active')
`

type TestQuery012Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery012(ctx context.Context, arg TestQuery012Params) error {
	_, err := q.db.Exec(ctx, TestQuery012, arg.ID, arg.BusinessID)
	return err
}

const TestQuery013 = `-- name: TestQuery013 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'excluded prompt', 'active')
`

type TestQuery013Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery013(ctx context.Context, arg TestQuery013Params) error {
	_, err := q.db.Exec(ctx, TestQuery013, arg.ID, arg.BusinessID)
	return err
}

const TestQuery014 = `-- name: TestQuery014 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'foreign prompt text', 'active')
`

type TestQuery014Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery014(ctx context.Context, arg TestQuery014Params) error {
	_, err := q.db.Exec(ctx, TestQuery014, arg.ID, arg.BusinessID)
	return err
}

const TestQuery015 = `-- name: TestQuery015 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-06', 'completed', 'wf-cite-a', now(), now())
`

type TestQuery015Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery015(ctx context.Context, arg TestQuery015Params) error {
	_, err := q.db.Exec(ctx, TestQuery015, arg.ID, arg.BusinessID)
	return err
}

const TestQuery016 = `-- name: TestQuery016 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'wf-cite-b', now())
`

type TestQuery016Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery016(ctx context.Context, arg TestQuery016Params) error {
	_, err := q.db.Exec(ctx, TestQuery016, arg.ID, arg.BusinessID)
	return err
}

const TestQuery017 = `-- name: TestQuery017 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text, requested_at, completed_at)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{}'::jsonb, '{"id":"r"}'::jsonb, 'text', now(), now())
`

type TestQuery017Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery017(ctx context.Context, arg TestQuery017Params) error {
	_, err := q.db.Exec(ctx, TestQuery017, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery018 = `-- name: TestQuery018 :exec
INSERT INTO result_analyses (prompt_result_id, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, ARRAY['useful']::text[], '[]'::jsonb, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery018(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery018, promptResultID)
	return err
}

const TestQuery019 = `-- name: TestQuery019 :exec
INSERT INTO citations (id, prompt_result_id, url, domain, title, subject, cite_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type TestQuery019Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Url            string
	Domain         string
	Title          *string
	Subject        string
	CiteOrder      int32
}

func (q *Queries) TestQuery019(ctx context.Context, arg TestQuery019Params) error {
	_, err := q.db.Exec(ctx, TestQuery019,
		arg.ID,
		arg.PromptResultID,
		arg.Url,
		arg.Domain,
		arg.Title,
		arg.Subject,
		arg.CiteOrder,
	)
	return err
}

const TestQuery020 = `-- name: TestQuery020 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery020(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery020, id)
	return err
}

const TestQuery021 = `-- name: TestQuery021 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery021(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery021, tenantID)
	return err
}

const TestQuery022 = `-- name: TestQuery022 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery022(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery022, id)
	return err
}

const TestQuery023 = `-- name: TestQuery023 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Atlas Clinic')
`

type TestQuery023Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery023(ctx context.Context, arg TestQuery023Params) error {
	_, err := q.db.Exec(ctx, TestQuery023, arg.ID, arg.TenantID)
	return err
}

const TestQuery024 = `-- name: TestQuery024 :exec
INSERT INTO prompts (id, business_id, text, status, created_at) VALUES ($1, $2, 'q', 'active', '2026-07-06T00:00:00Z')
`

type TestQuery024Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery024(ctx context.Context, arg TestQuery024Params) error {
	_, err := q.db.Exec(ctx, TestQuery024, arg.ID, arg.BusinessID)
	return err
}

const TestQuery025 = `-- name: TestQuery025 :exec
INSERT INTO competitors (id, business_id, name, aliases, suggested_aliases, source, status)
VALUES ($1, $2, 'Rival Clinic', ARRAY['rival clinic']::text[], ARRAY['Rival Medical']::text[], 'discovered', 'discovered')
`

type TestQuery025Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery025(ctx context.Context, arg TestQuery025Params) error {
	_, err := q.db.Exec(ctx, TestQuery025, arg.ID, arg.BusinessID)
	return err
}

const TestQuery026 = `-- name: TestQuery026 :exec
INSERT INTO competitors (id, business_id, name, source, status)
VALUES ($1, $2, 'Manual Rival', 'manual', 'tracked')
`

type TestQuery026Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery026(ctx context.Context, arg TestQuery026Params) error {
	_, err := q.db.Exec(ctx, TestQuery026, arg.ID, arg.BusinessID)
	return err
}

const TestQuery027 = `-- name: TestQuery027 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-06', 'completed', 'wf-a', now(), now())
`

type TestQuery027Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery027(ctx context.Context, arg TestQuery027Params) error {
	_, err := q.db.Exec(ctx, TestQuery027, arg.ID, arg.BusinessID)
	return err
}

const TestQuery028 = `-- name: TestQuery028 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'wf-b', now())
`

type TestQuery028Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery028(ctx context.Context, arg TestQuery028Params) error {
	_, err := q.db.Exec(ctx, TestQuery028, arg.ID, arg.BusinessID)
	return err
}

const TestQuery029 = `-- name: TestQuery029 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text, requested_at, completed_at)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{}'::jsonb, '{"id":"r"}'::jsonb, 'text', $4, $4)
`

type TestQuery029Params struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	PromptID    uuid.UUID
	RequestedAt time.Time
}

func (q *Queries) TestQuery029(ctx context.Context, arg TestQuery029Params) error {
	_, err := q.db.Exec(ctx, TestQuery029,
		arg.ID,
		arg.RunID,
		arg.PromptID,
		arg.RequestedAt,
	)
	return err
}

const TestQuery030 = `-- name: TestQuery030 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, error, request, requested_at, completed_at)
VALUES ($1, $2, $3, 'failed', 'boom', '{}'::jsonb, now(), now())
`

type TestQuery030Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery030(ctx context.Context, arg TestQuery030Params) error {
	_, err := q.db.Exec(ctx, TestQuery030, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery031 = `-- name: TestQuery031 :exec
INSERT INTO result_analyses (prompt_result_id, sentiment, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, $2, ARRAY[$3::text]::text[], '[]'::jsonb, 'gpt-5-mini', 1)
`

type TestQuery031Params struct {
	PromptResultID uuid.UUID
	Sentiment      *string
	Column3        string
}

func (q *Queries) TestQuery031(ctx context.Context, arg TestQuery031Params) error {
	_, err := q.db.Exec(ctx, TestQuery031, arg.PromptResultID, arg.Sentiment, arg.Column3)
	return err
}

const TestQuery032 = `-- name: TestQuery032 :exec
INSERT INTO citations (id, prompt_result_id, url, domain, subject, cite_order)
VALUES ($1, $2, 'https://x', $3, 'other', 0)
`

type TestQuery032Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	Domain         string
}

func (q *Queries) TestQuery032(ctx context.Context, arg TestQuery032Params) error {
	_, err := q.db.Exec(ctx, TestQuery032, arg.ID, arg.PromptResultID, arg.Domain)
	return err
}

const TestQuery033 = `-- name: TestQuery033 :exec
INSERT INTO mentions (id, prompt_result_id, subject, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'self', 'exact', $3, 'ex')
`

type TestQuery033Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	MentionOrder   int32
}

func (q *Queries) TestQuery033(ctx context.Context, arg TestQuery033Params) error {
	_, err := q.db.Exec(ctx, TestQuery033, arg.ID, arg.PromptResultID, arg.MentionOrder)
	return err
}

const TestQuery034 = `-- name: TestQuery034 :exec
INSERT INTO mentions (id, prompt_result_id, subject, competitor_id, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'competitor', $3, 'exact', $4, 'ex')
`

type TestQuery034Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
	MentionOrder   int32
}

func (q *Queries) TestQuery034(ctx context.Context, arg TestQuery034Params) error {
	_, err := q.db.Exec(ctx, TestQuery034,
		arg.ID,
		arg.PromptResultID,
		arg.CompetitorID,
		arg.MentionOrder,
	)
	return err
}

const TestQuery035 = `-- name: TestQuery035 :exec
UPDATE prompts SET status = 'retired', retired_at = '2026-07-20T10:00:00Z' WHERE id = $1
`

func (q *Queries) TestQuery035(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery035, id)
	return err
}

const TestQuery036 = `-- name: TestQuery036 :exec
INSERT INTO prompts (id, business_id, text, status, replaces_prompt_id, created_at)
VALUES ($1, $2, 'q2', 'active', $3, '2026-07-20T10:00:00Z')
`

type TestQuery036Params struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	ReplacesPromptID *uuid.UUID
}

func (q *Queries) TestQuery036(ctx context.Context, arg TestQuery036Params) error {
	_, err := q.db.Exec(ctx, TestQuery036, arg.ID, arg.BusinessID, arg.ReplacesPromptID)
	return err
}

const TestQuery037 = `-- name: TestQuery037 :exec
INSERT INTO prompts (id, business_id, text, status, created_at)
VALUES ($1, $2, 'q3', 'active', '2026-07-20T10:00:00Z')
`

type TestQuery037Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery037(ctx context.Context, arg TestQuery037Params) error {
	_, err := q.db.Exec(ctx, TestQuery037, arg.ID, arg.BusinessID)
	return err
}

const TestQuery038 = `-- name: TestQuery038 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery038(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery038, id)
	return err
}

const TestQuery039 = `-- name: TestQuery039 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery039(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery039, tenantID)
	return err
}

const TestQuery040 = `-- name: TestQuery040 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery040(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery040, id)
	return err
}

const TestQuery041 = `-- name: TestQuery041 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Atlas Clinic')
`

type TestQuery041Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery041(ctx context.Context, arg TestQuery041Params) error {
	_, err := q.db.Exec(ctx, TestQuery041, arg.ID, arg.TenantID)
	return err
}

const TestQuery042 = `-- name: TestQuery042 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery042Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery042(ctx context.Context, arg TestQuery042Params) error {
	_, err := q.db.Exec(ctx, TestQuery042, arg.ID, arg.BusinessID)
	return err
}

const TestQuery043 = `-- name: TestQuery043 :exec
INSERT INTO competitors (id, business_id, name, aliases, source, status)
VALUES ($1, $2, 'Rival Clinic', ARRAY['rival clinic']::text[], 'manual', 'tracked')
`

type TestQuery043Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery043(ctx context.Context, arg TestQuery043Params) error {
	_, err := q.db.Exec(ctx, TestQuery043, arg.ID, arg.BusinessID)
	return err
}

const TestQuery044 = `-- name: TestQuery044 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-06', 'completed', 'wf-zero-a', now(), now())
`

type TestQuery044Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery044(ctx context.Context, arg TestQuery044Params) error {
	_, err := q.db.Exec(ctx, TestQuery044, arg.ID, arg.BusinessID)
	return err
}

const TestQuery045 = `-- name: TestQuery045 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'wf-zero-b', now(), now())
`

type TestQuery045Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery045(ctx context.Context, arg TestQuery045Params) error {
	_, err := q.db.Exec(ctx, TestQuery045, arg.ID, arg.BusinessID)
	return err
}

const TestQuery046 = `-- name: TestQuery046 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text, requested_at, completed_at)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{}'::jsonb, '{"id":"r"}'::jsonb, 'text', $4, $4)
`

type TestQuery046Params struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	PromptID    uuid.UUID
	RequestedAt time.Time
}

func (q *Queries) TestQuery046(ctx context.Context, arg TestQuery046Params) error {
	_, err := q.db.Exec(ctx, TestQuery046,
		arg.ID,
		arg.RunID,
		arg.PromptID,
		arg.RequestedAt,
	)
	return err
}

const TestQuery047 = `-- name: TestQuery047 :exec
INSERT INTO result_analyses (prompt_result_id, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, ARRAY['useful']::text[], '[]'::jsonb, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery047(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery047, promptResultID)
	return err
}

const TestQuery048 = `-- name: TestQuery048 :exec
INSERT INTO mentions (id, prompt_result_id, subject, competitor_id, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'competitor', $3, 'exact', 0, 'Rival Clinic appears.')
`

type TestQuery048Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
}

func (q *Queries) TestQuery048(ctx context.Context, arg TestQuery048Params) error {
	_, err := q.db.Exec(ctx, TestQuery048, arg.ID, arg.PromptResultID, arg.CompetitorID)
	return err
}

const TestQuery049 = `-- name: TestQuery049 :exec
INSERT INTO tenants (id, name) VALUES ($1, $2)
`

type TestQuery049Params struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) TestQuery049(ctx context.Context, arg TestQuery049Params) error {
	_, err := q.db.Exec(ctx, TestQuery049, arg.ID, arg.Name)
	return err
}

const TestQuery050 = `-- name: TestQuery050 :exec
INSERT INTO subscriptions (tenant_id, plan_code, comped) VALUES ($1, 'starter', true)
`

func (q *Queries) TestQuery050(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery050, tenantID)
	return err
}

const TestQuery051 = `-- name: TestQuery051 :exec
DELETE FROM users WHERE tenant_id = $1
`

func (q *Queries) TestQuery051(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery051, tenantID)
	return err
}

const TestQuery052 = `-- name: TestQuery052 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery052(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery052, tenantID)
	return err
}

const TestQuery053 = `-- name: TestQuery053 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery053(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery053, id)
	return err
}

const TestQuery054 = `-- name: TestQuery054 :one
SELECT plan_code, comped FROM subscriptions WHERE tenant_id = $1
`

type TestQuery054Row struct {
	PlanCode string
	Comped   bool
}

func (q *Queries) TestQuery054(ctx context.Context, tenantID uuid.UUID) (TestQuery054Row, error) {
	row := q.db.QueryRow(ctx, TestQuery054, tenantID)
	var i TestQuery054Row
	err := row.Scan(&i.PlanCode, &i.Comped)
	return i, err
}

const TestQuery055 = `-- name: TestQuery055 :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) TestQuery055(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, TestQuery055, id)
	var password_hash *string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const TestQuery056 = `-- name: TestQuery056 :exec
DELETE FROM users WHERE tenant_id = $1
`

func (q *Queries) TestQuery056(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery056, tenantID)
	return err
}

const TestQuery057 = `-- name: TestQuery057 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery057(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery057, tenantID)
	return err
}

const TestQuery058 = `-- name: TestQuery058 :exec
DELETE FROM businesses WHERE tenant_id = $1
`

func (q *Queries) TestQuery058(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery058, tenantID)
	return err
}

const TestQuery059 = `-- name: TestQuery059 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery059(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery059, id)
	return err
}

const TestQuery060 = `-- name: TestQuery060 :one
SELECT plan_code, comped, stripe_customer_id, stripe_subscription_id, stripe_status FROM subscriptions WHERE tenant_id = $1
`

type TestQuery060Row struct {
	PlanCode             string
	Comped               bool
	StripeCustomerID     *string
	StripeSubscriptionID *string
	StripeStatus         *string
}

func (q *Queries) TestQuery060(ctx context.Context, tenantID uuid.UUID) (TestQuery060Row, error) {
	row := q.db.QueryRow(ctx, TestQuery060, tenantID)
	var i TestQuery060Row
	err := row.Scan(
		&i.PlanCode,
		&i.Comped,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeStatus,
	)
	return i, err
}

const TestQuery061 = `-- name: TestQuery061 :exec
DELETE FROM users WHERE tenant_id = $1
`

func (q *Queries) TestQuery061(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery061, tenantID)
	return err
}

const TestQuery062 = `-- name: TestQuery062 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery062(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery062, tenantID)
	return err
}

const TestQuery063 = `-- name: TestQuery063 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery063(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery063, id)
	return err
}

const TestQuery064 = `-- name: TestQuery064 :one
SELECT count(*) FROM tenants
`

func (q *Queries) TestQuery064(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery064)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery065 = `-- name: TestQuery065 :one
SELECT count(*) FROM tenants
`

func (q *Queries) TestQuery065(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery065)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery066 = `-- name: TestQuery066 :exec
DELETE FROM mentions WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery066(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery066, promptResultID)
	return err
}

const TestQuery067 = `-- name: TestQuery067 :exec
DELETE FROM citations WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery067(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery067, promptResultID)
	return err
}

const TestQuery068 = `-- name: TestQuery068 :exec
DELETE FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery068(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery068, promptResultID)
	return err
}

const TestQuery069 = `-- name: TestQuery069 :exec
DELETE FROM competitors WHERE id = $1
`

func (q *Queries) TestQuery069(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery069, id)
	return err
}

const TestQuery070 = `-- name: TestQuery070 :exec
DELETE FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery070(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery070, id)
	return err
}

const TestQuery071 = `-- name: TestQuery071 :exec
DELETE FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery071(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery071, id)
	return err
}

const TestQuery072 = `-- name: TestQuery072 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery072(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery072, id)
	return err
}

const TestQuery073 = `-- name: TestQuery073 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery073(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery073, id)
	return err
}

const TestQuery074 = `-- name: TestQuery074 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery074(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery074, tenantID)
	return err
}

const TestQuery075 = `-- name: TestQuery075 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery075(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery075, id)
	return err
}

const TestQuery076 = `-- name: TestQuery076 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Analysis Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery076Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery076(ctx context.Context, arg TestQuery076Params) error {
	_, err := q.db.Exec(ctx, TestQuery076, arg.ID, arg.TenantID)
	return err
}

const TestQuery077 = `-- name: TestQuery077 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery077Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery077(ctx context.Context, arg TestQuery077Params) error {
	_, err := q.db.Exec(ctx, TestQuery077, arg.ID, arg.BusinessID)
	return err
}

const TestQuery078 = `-- name: TestQuery078 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'analysis-workflow', now())
`

type TestQuery078Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery078(ctx context.Context, arg TestQuery078Params) error {
	_, err := q.db.Exec(ctx, TestQuery078, arg.ID, arg.BusinessID)
	return err
}

const TestQuery079 = `-- name: TestQuery079 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{"model":"gpt-5-mini"}'::jsonb, '{"id":"resp_1"}'::jsonb, 'Analysis Clinic and Rival Clinic are options.')
`

type TestQuery079Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery079(ctx context.Context, arg TestQuery079Params) error {
	_, err := q.db.Exec(ctx, TestQuery079, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery080 = `-- name: TestQuery080 :exec
INSERT INTO competitors (id, business_id, name, aliases, source, status)
VALUES ($1, $2, 'Rival Clinic', ARRAY['rival clinic']::text[], 'discovered', 'discovered')
`

type TestQuery080Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery080(ctx context.Context, arg TestQuery080Params) error {
	_, err := q.db.Exec(ctx, TestQuery080, arg.ID, arg.BusinessID)
	return err
}

const TestQuery081 = `-- name: TestQuery081 :exec
INSERT INTO result_analyses (prompt_result_id, sentiment, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, 'positive', ARRAY['friendly']::text[], '["Analysis Clinic is a good option."]'::jsonb, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery081(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery081, promptResultID)
	return err
}

const TestQuery082 = `-- name: TestQuery082 :exec
INSERT INTO citations (id, prompt_result_id, url, domain, subject, cite_order)
VALUES ($1, $2, 'https://example.com/x', 'example.com', 'business', 0)
`

type TestQuery082Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery082(ctx context.Context, arg TestQuery082Params) error {
	_, err := q.db.Exec(ctx, TestQuery082, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery083 = `-- name: TestQuery083 :exec
INSERT INTO mentions (id, prompt_result_id, subject, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'self', 'exact', 0, 'Analysis Clinic ... options.')
`

type TestQuery083Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery083(ctx context.Context, arg TestQuery083Params) error {
	_, err := q.db.Exec(ctx, TestQuery083, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery084 = `-- name: TestQuery084 :exec
INSERT INTO mentions (id, prompt_result_id, subject, competitor_id, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'competitor', $3, 'exact', 1, 'Rival Clinic ... options.')
`

type TestQuery084Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
}

func (q *Queries) TestQuery084(ctx context.Context, arg TestQuery084Params) error {
	_, err := q.db.Exec(ctx, TestQuery084, arg.ID, arg.PromptResultID, arg.CompetitorID)
	return err
}

const TestQuery085 = `-- name: TestQuery085 :exec
INSERT INTO mentions (id, prompt_result_id, subject, competitor_id, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'self', $3, 'exact', 2, 'bad')
`

type TestQuery085Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
}

func (q *Queries) TestQuery085(ctx context.Context, arg TestQuery085Params) error {
	_, err := q.db.Exec(ctx, TestQuery085, arg.ID, arg.PromptResultID, arg.CompetitorID)
	return err
}

const TestQuery086 = `-- name: TestQuery086 :exec
INSERT INTO mentions (id, prompt_result_id, subject, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'competitor', 'exact', 2, 'bad')
`

type TestQuery086Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery086(ctx context.Context, arg TestQuery086Params) error {
	_, err := q.db.Exec(ctx, TestQuery086, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery087 = `-- name: TestQuery087 :one
SELECT count(*) FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery087(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery087, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery088 = `-- name: TestQuery088 :one
SELECT count(*) FROM citations WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery088(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery088, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery089 = `-- name: TestQuery089 :one
SELECT count(*) FROM mentions WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery089(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery089, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery090 = `-- name: TestQuery090 :one
SELECT count(*) FROM mentions WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery090(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery090, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery091 = `-- name: TestQuery091 :one
SELECT count(*) FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery091(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery091, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery092 = `-- name: TestQuery092 :one
SELECT count(*) FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery092(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery092, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery093 = `-- name: TestQuery093 :exec
DELETE FROM competitors WHERE business_id IN ($1, $2)
`

type TestQuery093Params struct {
	BusinessID   uuid.UUID
	BusinessID_2 uuid.UUID
}

func (q *Queries) TestQuery093(ctx context.Context, arg TestQuery093Params) error {
	_, err := q.db.Exec(ctx, TestQuery093, arg.BusinessID, arg.BusinessID_2)
	return err
}

const TestQuery094 = `-- name: TestQuery094 :exec
DELETE FROM businesses WHERE id IN ($1, $2)
`

type TestQuery094Params struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

func (q *Queries) TestQuery094(ctx context.Context, arg TestQuery094Params) error {
	_, err := q.db.Exec(ctx, TestQuery094, arg.ID, arg.ID_2)
	return err
}

const TestQuery095 = `-- name: TestQuery095 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery095(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery095, tenantID)
	return err
}

const TestQuery096 = `-- name: TestQuery096 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery096(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery096, id)
	return err
}

const TestQuery097 = `-- name: TestQuery097 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Atlas Clinic')
`

type TestQuery097Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery097(ctx context.Context, arg TestQuery097Params) error {
	_, err := q.db.Exec(ctx, TestQuery097, arg.ID, arg.TenantID)
	return err
}

const TestQuery098 = `-- name: TestQuery098 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Other Clinic')
`

type TestQuery098Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery098(ctx context.Context, arg TestQuery098Params) error {
	_, err := q.db.Exec(ctx, TestQuery098, arg.ID, arg.TenantID)
	return err
}

const TestQuery099 = `-- name: TestQuery099 :exec
INSERT INTO competitors (id, business_id, name, aliases, source, status)
VALUES ($1, $2, 'Discovered Co', ARRAY['disco']::text[], 'discovered', 'discovered')
`

type TestQuery099Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery099(ctx context.Context, arg TestQuery099Params) error {
	_, err := q.db.Exec(ctx, TestQuery099, arg.ID, arg.BusinessID)
	return err
}

const TestQuery100 = `-- name: TestQuery100 :exec
INSERT INTO competitors (id, business_id, name, source, status)
VALUES ($1, $2, 'Tracked Co', 'manual', 'tracked')
`

type TestQuery100Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery100(ctx context.Context, arg TestQuery100Params) error {
	_, err := q.db.Exec(ctx, TestQuery100, arg.ID, arg.BusinessID)
	return err
}

const TestQuery101 = `-- name: TestQuery101 :exec
INSERT INTO competitors (id, business_id, name, source, status)
VALUES ($1, $2, 'Dismissed Co', 'discovered', 'dismissed')
`

type TestQuery101Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery101(ctx context.Context, arg TestQuery101Params) error {
	_, err := q.db.Exec(ctx, TestQuery101, arg.ID, arg.BusinessID)
	return err
}

const TestQuery102 = `-- name: TestQuery102 :exec
INSERT INTO competitors (id, business_id, name, source, status)
VALUES ($1, $2, 'Other Co', 'discovered', 'discovered')
`

type TestQuery102Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery102(ctx context.Context, arg TestQuery102Params) error {
	_, err := q.db.Exec(ctx, TestQuery102, arg.ID, arg.BusinessID)
	return err
}

const TestQuery103 = `-- name: TestQuery103 :exec
DELETE FROM prompts WHERE business_id IN ($1, $2)
`

type TestQuery103Params struct {
	BusinessID   uuid.UUID
	BusinessID_2 uuid.UUID
}

func (q *Queries) TestQuery103(ctx context.Context, arg TestQuery103Params) error {
	_, err := q.db.Exec(ctx, TestQuery103, arg.BusinessID, arg.BusinessID_2)
	return err
}

const TestQuery104 = `-- name: TestQuery104 :exec
DELETE FROM profile_proposals WHERE business_id IN ($1, $2)
`

type TestQuery104Params struct {
	BusinessID   uuid.UUID
	BusinessID_2 uuid.UUID
}

func (q *Queries) TestQuery104(ctx context.Context, arg TestQuery104Params) error {
	_, err := q.db.Exec(ctx, TestQuery104, arg.BusinessID, arg.BusinessID_2)
	return err
}

const TestQuery105 = `-- name: TestQuery105 :exec
DELETE FROM businesses WHERE id IN ($1, $2)
`

type TestQuery105Params struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

func (q *Queries) TestQuery105(ctx context.Context, arg TestQuery105Params) error {
	_, err := q.db.Exec(ctx, TestQuery105, arg.ID, arg.ID_2)
	return err
}

const TestQuery106 = `-- name: TestQuery106 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery106(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery106, tenantID)
	return err
}

const TestQuery107 = `-- name: TestQuery107 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery107(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery107, id)
	return err
}

const TestQuery108 = `-- name: TestQuery108 :exec
INSERT INTO businesses (id, tenant_id, status, name, website)
VALUES ($1, $2, 'draft', 'Draft Clinic', 'https://draft.example')
`

type TestQuery108Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery108(ctx context.Context, arg TestQuery108Params) error {
	_, err := q.db.Exec(ctx, TestQuery108, arg.ID, arg.TenantID)
	return err
}

const TestQuery109 = `-- name: TestQuery109 :exec
INSERT INTO profile_proposals (id, business_id, payload, status)
VALUES ($1, $2, '{"low_confidence":false}'::jsonb, 'pending')
`

type TestQuery109Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery109(ctx context.Context, arg TestQuery109Params) error {
	_, err := q.db.Exec(ctx, TestQuery109, arg.ID, arg.BusinessID)
	return err
}

const TestQuery110 = `-- name: TestQuery110 :exec
INSERT INTO businesses (id, tenant_id, status, name)
VALUES ($1, $2, 'draft', 'Manual Clinic')
`

type TestQuery110Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery110(ctx context.Context, arg TestQuery110Params) error {
	_, err := q.db.Exec(ctx, TestQuery110, arg.ID, arg.TenantID)
	return err
}

const TestQuery111 = `-- name: TestQuery111 :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) TestQuery111(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery111, userID)
	return err
}

const TestQuery112 = `-- name: TestQuery112 :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) TestQuery112(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery112, id)
	return err
}

const TestQuery113 = `-- name: TestQuery113 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery113(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery113, tenantID)
	return err
}

const TestQuery114 = `-- name: TestQuery114 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery114(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery114, id)
	return err
}

const TestQuery115 = `-- name: TestQuery115 :exec
INSERT INTO users (id, tenant_id, email, password_hash) VALUES ($1, $2, $3, $4)
`

type TestQuery115Params struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash *string
}

func (q *Queries) TestQuery115(ctx context.Context, arg TestQuery115Params) error {
	_, err := q.db.Exec(ctx, TestQuery115,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const TestQuery116 = `-- name: TestQuery116 :exec
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, now() - interval '1 minute')
`

type TestQuery116Params struct {
	TokenHash []byte
	UserID    uuid.UUID
}

func (q *Queries) TestQuery116(ctx context.Context, arg TestQuery116Params) error {
	_, err := q.db.Exec(ctx, TestQuery116, arg.TokenHash, arg.UserID)
	return err
}

const TestQuery117 = `-- name: TestQuery117 :one
SELECT count(*) FROM sessions WHERE user_id = $1 AND expires_at <= now()
`

func (q *Queries) TestQuery117(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery117, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery118 = `-- name: TestQuery118 :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) TestQuery118(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery118, id)
	return err
}

const TestQuery119 = `-- name: TestQuery119 :one
SELECT count(*) FROM sessions WHERE user_id = $1
`

func (q *Queries) TestQuery119(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery119, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery120 = `-- name: TestQuery120 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery120(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery120, id)
	return err
}

const TestQuery121 = `-- name: TestQuery121 :exec
DELETE FROM subscriptions WHERE tenant_id IN ($1, $2)
`

type TestQuery121Params struct {
	TenantID   uuid.UUID
	TenantID_2 uuid.UUID
}

func (q *Queries) TestQuery121(ctx context.Context, arg TestQuery121Params) error {
	_, err := q.db.Exec(ctx, TestQuery121, arg.TenantID, arg.TenantID_2)
	return err
}

const TestQuery122 = `-- name: TestQuery122 :exec
DELETE FROM tenants WHERE id IN ($1, $2)
`

type TestQuery122Params struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

func (q *Queries) TestQuery122(ctx context.Context, arg TestQuery122Params) error {
	_, err := q.db.Exec(ctx, TestQuery122, arg.ID, arg.ID_2)
	return err
}

const TestQuery123 = `-- name: TestQuery123 :exec
INSERT INTO businesses
(id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Owner Clinic', 'clinic', '{"country":"SG"}', now())
`

type TestQuery123Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery123(ctx context.Context, arg TestQuery123Params) error {
	_, err := q.db.Exec(ctx, TestQuery123, arg.ID, arg.TenantID)
	return err
}

const TestQuery124 = `-- name: TestQuery124 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $2, 'best clinic', 'active')
`

type TestQuery124Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery124(ctx context.Context, arg TestQuery124Params) error {
	_, err := q.db.Exec(ctx, TestQuery124, arg.ID, arg.BusinessID)
	return err
}

const TestQuery125 = `-- name: TestQuery125 :exec
INSERT INTO monitoring_runs
(id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-20', 'completed', 'competitor-history', now(), now())
`

type TestQuery125Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery125(ctx context.Context, arg TestQuery125Params) error {
	_, err := q.db.Exec(ctx, TestQuery125, arg.ID, arg.BusinessID)
	return err
}

const TestQuery126 = `-- name: TestQuery126 :exec
INSERT INTO prompt_results
(id, run_id, prompt_id, status, model, request, raw_response, response_text, requested_at, completed_at)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{}', '{}', 'text', now(), now())
`

type TestQuery126Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery126(ctx context.Context, arg TestQuery126Params) error {
	_, err := q.db.Exec(ctx, TestQuery126, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery127 = `-- name: TestQuery127 :exec
INSERT INTO result_analyses
(prompt_result_id, analysis_model, extraction_version)
VALUES ($1, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery127(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery127, promptResultID)
	return err
}

const TestQuery128 = `-- name: TestQuery128 :exec
INSERT INTO mentions
(id, prompt_result_id, subject, competitor_id, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'competitor', $3, 'exact', 0, 'Rival Clinic')
`

type TestQuery128Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
}

func (q *Queries) TestQuery128(ctx context.Context, arg TestQuery128Params) error {
	_, err := q.db.Exec(ctx, TestQuery128, arg.ID, arg.PromptResultID, arg.CompetitorID)
	return err
}

const TestQuery129 = `-- name: TestQuery129 :exec
UPDATE competitors
SET suggested_aliases = ARRAY['Private Alias']::text[]
WHERE id = $1
`

func (q *Queries) TestQuery129(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery129, id)
	return err
}

const TestQuery130 = `-- name: TestQuery130 :one
SELECT count(*) FROM mentions WHERE competitor_id = $1
`

func (q *Queries) TestQuery130(ctx context.Context, competitorID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery130, competitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery131 = `-- name: TestQuery131 :exec
DELETE FROM profile_proposals WHERE business_id = $1
`

func (q *Queries) TestQuery131(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery131, businessID)
	return err
}

const TestQuery132 = `-- name: TestQuery132 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery132(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery132, id)
	return err
}

const TestQuery133 = `-- name: TestQuery133 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery133(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery133, tenantID)
	return err
}

const TestQuery134 = `-- name: TestQuery134 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery134(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery134, id)
	return err
}

const TestQuery135 = `-- name: TestQuery135 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Proposal Clinic')
`

type TestQuery135Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery135(ctx context.Context, arg TestQuery135Params) error {
	_, err := q.db.Exec(ctx, TestQuery135, arg.ID, arg.TenantID)
	return err
}

const TestQuery136 = `-- name: TestQuery136 :exec
DELETE FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery136(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery136, businessID)
	return err
}

const TestQuery137 = `-- name: TestQuery137 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery137(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery137, id)
	return err
}

const TestQuery138 = `-- name: TestQuery138 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery138(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery138, tenantID)
	return err
}

const TestQuery139 = `-- name: TestQuery139 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery139(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery139, id)
	return err
}

const TestQuery140 = `-- name: TestQuery140 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Prompt Limit Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery140Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery140(ctx context.Context, arg TestQuery140Params) error {
	_, err := q.db.Exec(ctx, TestQuery140, arg.ID, arg.TenantID)
	return err
}

const TestQuery141 = `-- name: TestQuery141 :one
SELECT count(*) FROM prompts WHERE business_id = $1 AND status = 'active'
`

func (q *Queries) TestQuery141(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery141, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery142 = `-- name: TestQuery142 :exec
DELETE FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery142(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery142, businessID)
	return err
}

const TestQuery143 = `-- name: TestQuery143 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery143(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery143, id)
	return err
}

const TestQuery144 = `-- name: TestQuery144 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery144(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery144, tenantID)
	return err
}

const TestQuery145 = `-- name: TestQuery145 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery145(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery145, id)
	return err
}

const TestQuery146 = `-- name: TestQuery146 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Replace Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery146Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery146(ctx context.Context, arg TestQuery146Params) error {
	_, err := q.db.Exec(ctx, TestQuery146, arg.ID, arg.TenantID)
	return err
}

const TestQuery147 = `-- name: TestQuery147 :one
SELECT status FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery147(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, TestQuery147, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const TestQuery148 = `-- name: TestQuery148 :one
SELECT count(*) FROM prompts WHERE business_id = $1 AND status = 'active'
`

func (q *Queries) TestQuery148(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery148, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery149 = `-- name: TestQuery149 :exec
DELETE FROM prompt_results WHERE run_id IN (SELECT id FROM monitoring_runs WHERE business_id = $1)
`

func (q *Queries) TestQuery149(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery149, businessID)
	return err
}

const TestQuery150 = `-- name: TestQuery150 :exec
DELETE FROM competitors WHERE business_id = $1
`

func (q *Queries) TestQuery150(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery150, businessID)
	return err
}

const TestQuery151 = `-- name: TestQuery151 :exec
DELETE FROM monitoring_runs WHERE business_id = $1
`

func (q *Queries) TestQuery151(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery151, businessID)
	return err
}

const TestQuery152 = `-- name: TestQuery152 :exec
DELETE FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery152(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery152, businessID)
	return err
}

const TestQuery153 = `-- name: TestQuery153 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery153(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery153, id)
	return err
}

const TestQuery154 = `-- name: TestQuery154 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery154(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery154, tenantID)
	return err
}

const TestQuery155 = `-- name: TestQuery155 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery155(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery155, id)
	return err
}

const TestQuery156 = `-- name: TestQuery156 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Result Analysis Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery156Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery156(ctx context.Context, arg TestQuery156Params) error {
	_, err := q.db.Exec(ctx, TestQuery156, arg.ID, arg.TenantID)
	return err
}

const TestQuery157 = `-- name: TestQuery157 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery157Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery157(ctx context.Context, arg TestQuery157Params) error {
	_, err := q.db.Exec(ctx, TestQuery157, arg.ID, arg.BusinessID)
	return err
}

const TestQuery158 = `-- name: TestQuery158 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'cheapest clinic near me', 'active')
`

type TestQuery158Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery158(ctx context.Context, arg TestQuery158Params) error {
	_, err := q.db.Exec(ctx, TestQuery158, arg.ID, arg.BusinessID)
	return err
}

const TestQuery159 = `-- name: TestQuery159 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at, analysis_completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'result-analysis-workflow', now(), now())
`

type TestQuery159Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery159(ctx context.Context, arg TestQuery159Params) error {
	_, err := q.db.Exec(ctx, TestQuery159, arg.ID, arg.BusinessID)
	return err
}

const TestQuery160 = `-- name: TestQuery160 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{"model":"gpt-5-mini"}'::jsonb, '{"id":"resp_1"}'::jsonb, 'Clinic and Rival are options.')
`

type TestQuery160Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery160(ctx context.Context, arg TestQuery160Params) error {
	_, err := q.db.Exec(ctx, TestQuery160, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery161 = `-- name: TestQuery161 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{"model":"gpt-5-mini"}'::jsonb, '{"id":"resp_2"}'::jsonb, 'No mention here.')
`

type TestQuery161Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery161(ctx context.Context, arg TestQuery161Params) error {
	_, err := q.db.Exec(ctx, TestQuery161, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery162 = `-- name: TestQuery162 :exec
INSERT INTO competitors (id, business_id, name, source, status)
VALUES ($1, $2, 'Rival Clinic', 'discovered', 'discovered')
`

type TestQuery162Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery162(ctx context.Context, arg TestQuery162Params) error {
	_, err := q.db.Exec(ctx, TestQuery162, arg.ID, arg.BusinessID)
	return err
}

const TestQuery163 = `-- name: TestQuery163 :exec
INSERT INTO result_analyses (prompt_result_id, sentiment, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, 'positive', ARRAY['friendly','affordable']::text[], '["Clinic is a good option."]'::jsonb, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery163(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery163, promptResultID)
	return err
}

const TestQuery164 = `-- name: TestQuery164 :exec
INSERT INTO mentions (id, prompt_result_id, subject, matched_by, mention_order, verbatim_name, excerpt)
VALUES ($1, $2, 'self', 'exact', 0, 'Atlas Clinic', 'Clinic ... options.')
`

type TestQuery164Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery164(ctx context.Context, arg TestQuery164Params) error {
	_, err := q.db.Exec(ctx, TestQuery164, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery165 = `-- name: TestQuery165 :exec
INSERT INTO mentions (id, prompt_result_id, subject, competitor_id, matched_by, mention_order, verbatim_name, excerpt)
VALUES ($1, $2, 'competitor', $3, 'llm', 1, 'Rival Clinic', 'Rival ... options.')
`

type TestQuery165Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
	CompetitorID   *uuid.UUID
}

func (q *Queries) TestQuery165(ctx context.Context, arg TestQuery165Params) error {
	_, err := q.db.Exec(ctx, TestQuery165, arg.ID, arg.PromptResultID, arg.CompetitorID)
	return err
}

const TestQuery166 = `-- name: TestQuery166 :exec
INSERT INTO citations (id, prompt_result_id, url, domain, title, cite_order, subject)
VALUES ($1, $2, 'https://example.com/x', 'example.com', 'Example', 0, 'business')
`

type TestQuery166Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery166(ctx context.Context, arg TestQuery166Params) error {
	_, err := q.db.Exec(ctx, TestQuery166, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery167 = `-- name: TestQuery167 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{"model":"gpt-5-mini"}'::jsonb, '{"id":"resp_1"}'::jsonb, 'Clinic is an option.')
`

type TestQuery167Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery167(ctx context.Context, arg TestQuery167Params) error {
	_, err := q.db.Exec(ctx, TestQuery167, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery168 = `-- name: TestQuery168 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5-mini', '{"model":"gpt-5-mini"}'::jsonb, '{"id":"resp_2"}'::jsonb, 'Nobody relevant.')
`

type TestQuery168Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery168(ctx context.Context, arg TestQuery168Params) error {
	_, err := q.db.Exec(ctx, TestQuery168, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery169 = `-- name: TestQuery169 :exec
INSERT INTO result_analyses (prompt_result_id, sentiment, keywords, excerpts, analysis_model, extraction_version)
VALUES ($1, 'positive', '{}'::text[], '[]'::jsonb, 'gpt-5-mini', 1)
`

func (q *Queries) TestQuery169(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery169, promptResultID)
	return err
}

const TestQuery170 = `-- name: TestQuery170 :exec
INSERT INTO mentions (id, prompt_result_id, subject, matched_by, mention_order, excerpt)
VALUES ($1, $2, 'self', 'exact', 0, 'Clinic ... option.')
`

type TestQuery170Params struct {
	ID             uuid.UUID
	PromptResultID uuid.UUID
}

func (q *Queries) TestQuery170(ctx context.Context, arg TestQuery170Params) error {
	_, err := q.db.Exec(ctx, TestQuery170, arg.ID, arg.PromptResultID)
	return err
}

const TestQuery171 = `-- name: TestQuery171 :exec
DELETE FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery171(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery171, id)
	return err
}

const TestQuery172 = `-- name: TestQuery172 :exec
DELETE FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery172(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery172, id)
	return err
}

const TestQuery173 = `-- name: TestQuery173 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery173(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery173, id)
	return err
}

const TestQuery174 = `-- name: TestQuery174 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery174(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery174, id)
	return err
}

const TestQuery175 = `-- name: TestQuery175 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery175(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery175, tenantID)
	return err
}

const TestQuery176 = `-- name: TestQuery176 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery176(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery176, id)
	return err
}

const TestQuery177 = `-- name: TestQuery177 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Runs Results Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery177Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery177(ctx context.Context, arg TestQuery177Params) error {
	_, err := q.db.Exec(ctx, TestQuery177, arg.ID, arg.TenantID)
	return err
}

const TestQuery178 = `-- name: TestQuery178 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery178Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery178(ctx context.Context, arg TestQuery178Params) error {
	_, err := q.db.Exec(ctx, TestQuery178, arg.ID, arg.BusinessID)
	return err
}

const TestQuery179 = `-- name: TestQuery179 :exec
INSERT INTO monitoring_runs (
  id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at
) VALUES (
  $1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'runs-results-workflow', now()
)
`

type TestQuery179Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery179(ctx context.Context, arg TestQuery179Params) error {
	_, err := q.db.Exec(ctx, TestQuery179, arg.ID, arg.BusinessID)
	return err
}

const TestQuery180 = `-- name: TestQuery180 :exec
INSERT INTO prompt_results (
  id, run_id, prompt_id, status, model, request, raw_response, response_text
) VALUES (
  $1,
  $2,
  $3,
  'succeeded',
  'gpt-5-mini-2026-07-01',
  '{"model":"gpt-5-mini","user_location":{"country":"SG"}}'::jsonb,
  '{"id":"resp_1","model":"gpt-5-mini-2026-07-01"}'::jsonb,
  'Runs Results Clinic is a good option.'
)
`

type TestQuery180Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery180(ctx context.Context, arg TestQuery180Params) error {
	_, err := q.db.Exec(ctx, TestQuery180, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery181 = `-- name: TestQuery181 :exec
INSERT INTO monitoring_runs (
  id, business_id, platform, trigger, scheduled_for, status, workflow_id
) VALUES (
  $1, $2, 'chatgpt', 'manual', '2026-07-13', 'running', 'runs-results-workflow-duplicate'
)
`

type TestQuery181Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery181(ctx context.Context, arg TestQuery181Params) error {
	_, err := q.db.Exec(ctx, TestQuery181, arg.ID, arg.BusinessID)
	return err
}

const TestQuery182 = `-- name: TestQuery182 :exec
INSERT INTO prompt_results (
  id, run_id, prompt_id, status, model, request, raw_response, response_text
) VALUES (
  $1,
  $2,
  $3,
  'succeeded',
  'gpt-5-mini-2026-07-01',
  '{"model":"gpt-5-mini"}'::jsonb,
  '{"id":"resp_2"}'::jsonb,
  'Duplicate response.'
)
`

type TestQuery182Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery182(ctx context.Context, arg TestQuery182Params) error {
	_, err := q.db.Exec(ctx, TestQuery182, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery183 = `-- name: TestQuery183 :exec
UPDATE prompt_results SET response_text = 'Changed response.' WHERE id = $1
`

func (q *Queries) TestQuery183(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery183, id)
	return err
}

const TestQuery184 = `-- name: TestQuery184 :exec
DELETE FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery184(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery184, id)
	return err
}

const TestQuery185 = `-- name: TestQuery185 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery185(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery185, id)
	return err
}

const TestQuery186 = `-- name: TestQuery186 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $2, 'cheapest clinic near me', 'active')
`

type TestQuery186Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery186(ctx context.Context, arg TestQuery186Params) error {
	_, err := q.db.Exec(ctx, TestQuery186, arg.ID, arg.BusinessID)
	return err
}

const TestQuery187 = `-- name: TestQuery187 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, request, error)
VALUES ($1, $2, $3, 'failed', '{"model":"gpt-5-mini"}'::jsonb, 'openai: timeout')
`

type TestQuery187Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery187(ctx context.Context, arg TestQuery187Params) error {
	_, err := q.db.Exec(ctx, TestQuery187, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery188 = `-- name: TestQuery188 :exec
DELETE FROM prompt_results WHERE run_id = $1
`

func (q *Queries) TestQuery188(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery188, runID)
	return err
}

const TestQuery189 = `-- name: TestQuery189 :exec
DELETE FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery189(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery189, id)
	return err
}

const TestQuery190 = `-- name: TestQuery190 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery190(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery190, id)
	return err
}

const TestQuery191 = `-- name: TestQuery191 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery191(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery191, id)
	return err
}

const TestQuery192 = `-- name: TestQuery192 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery192(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery192, tenantID)
	return err
}

const TestQuery193 = `-- name: TestQuery193 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery193(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery193, id)
	return err
}

const TestQuery194 = `-- name: TestQuery194 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Finalize Partial Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery194Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery194(ctx context.Context, arg TestQuery194Params) error {
	_, err := q.db.Exec(ctx, TestQuery194, arg.ID, arg.TenantID)
	return err
}

const TestQuery195 = `-- name: TestQuery195 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery195Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery195(ctx context.Context, arg TestQuery195Params) error {
	_, err := q.db.Exec(ctx, TestQuery195, arg.ID, arg.BusinessID)
	return err
}

const TestQuery196 = `-- name: TestQuery196 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery196(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery196, id)
	return err
}

const TestQuery197 = `-- name: TestQuery197 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $2, 'cheapest clinic near me', 'active')
`

type TestQuery197Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery197(ctx context.Context, arg TestQuery197Params) error {
	_, err := q.db.Exec(ctx, TestQuery197, arg.ID, arg.BusinessID)
	return err
}

const TestQuery198 = `-- name: TestQuery198 :exec
DELETE FROM prompt_results WHERE run_id IN (SELECT id FROM monitoring_runs WHERE business_id = $1)
`

func (q *Queries) TestQuery198(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery198, businessID)
	return err
}

const TestQuery199 = `-- name: TestQuery199 :exec
DELETE FROM monitoring_runs WHERE business_id = $1
`

func (q *Queries) TestQuery199(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery199, businessID)
	return err
}

const TestQuery200 = `-- name: TestQuery200 :exec
DELETE FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery200(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery200, businessID)
	return err
}

const TestQuery201 = `-- name: TestQuery201 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery201(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery201, id)
	return err
}

const TestQuery202 = `-- name: TestQuery202 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery202(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery202, tenantID)
	return err
}

const TestQuery203 = `-- name: TestQuery203 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery203(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery203, id)
	return err
}

const TestQuery204 = `-- name: TestQuery204 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'List Runs Counts Clinic', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery204Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery204(ctx context.Context, arg TestQuery204Params) error {
	_, err := q.db.Exec(ctx, TestQuery204, arg.ID, arg.TenantID)
	return err
}

const TestQuery205 = `-- name: TestQuery205 :exec
INSERT INTO prompts (id, business_id, text, status)
VALUES ($1, $4, 'a', 'active'), ($2, $4, 'b', 'active'), ($3, $4, 'c', 'active')
`

type TestQuery205Params struct {
	ID         uuid.UUID
	ID_2       uuid.UUID
	ID_3       uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery205(ctx context.Context, arg TestQuery205Params) error {
	_, err := q.db.Exec(ctx, TestQuery205,
		arg.ID,
		arg.ID_2,
		arg.ID_3,
		arg.BusinessID,
	)
	return err
}

const TestQuery206 = `-- name: TestQuery206 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, expected_results, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-20', 'partial', 'run-with-results', 3, now()),
       ($3, $2, 'chatgpt', 'scheduled', '2026-07-13', 'running', 'run-with-no-results', 2, NULL)
`

type TestQuery206Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	ID_2       uuid.UUID
}

func (q *Queries) TestQuery206(ctx context.Context, arg TestQuery206Params) error {
	_, err := q.db.Exec(ctx, TestQuery206, arg.ID, arg.BusinessID, arg.ID_2)
	return err
}

const TestQuery207 = `-- name: TestQuery207 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $3, $4, 'succeeded', 'gpt-5-mini-2026-07-01', '{}'::jsonb, '{}'::jsonb, 'ok'),
       ($2, $3, $5, 'succeeded', 'gpt-5-mini-2026-07-01', '{}'::jsonb, '{}'::jsonb, 'ok')
`

type TestQuery207Params struct {
	ID         uuid.UUID
	ID_2       uuid.UUID
	RunID      uuid.UUID
	PromptID   uuid.UUID
	PromptID_2 uuid.UUID
}

func (q *Queries) TestQuery207(ctx context.Context, arg TestQuery207Params) error {
	_, err := q.db.Exec(ctx, TestQuery207,
		arg.ID,
		arg.ID_2,
		arg.RunID,
		arg.PromptID,
		arg.PromptID_2,
	)
	return err
}

const TestQuery208 = `-- name: TestQuery208 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, request, error)
VALUES ($1, $2, $3, 'failed', '{}'::jsonb, 'openai: timeout')
`

type TestQuery208Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery208(ctx context.Context, arg TestQuery208Params) error {
	_, err := q.db.Exec(ctx, TestQuery208, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery209 = `-- name: TestQuery209 :exec
INSERT INTO result_analyses (prompt_result_id, analysis_model, extraction_version)
VALUES ($1, 'gpt-5-mini-2026-07-01', 1)
`

func (q *Queries) TestQuery209(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery209, promptResultID)
	return err
}

const TestQuery210 = `-- name: TestQuery210 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery210(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery210, tenantID)
	return err
}

const TestQuery211 = `-- name: TestQuery211 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery211(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery211, id)
	return err
}

const TestQuery212 = `-- name: TestQuery212 :exec
INSERT INTO tenants (id, name) VALUES ($1, 'Subscription Tenant')
`

func (q *Queries) TestQuery212(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery212, id)
	return err
}

const TestQuery213 = `-- name: TestQuery213 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery213(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery213, tenantID)
	return err
}

const TestQuery214 = `-- name: TestQuery214 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery214(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery214, id)
	return err
}

const TestQuery215 = `-- name: TestQuery215 :exec
INSERT INTO tenants (id, name) VALUES ($1, 'Customer Id Tenant')
`

func (q *Queries) TestQuery215(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery215, id)
	return err
}

const TestQuery216 = `-- name: TestQuery216 :exec
DELETE FROM prompt_results WHERE run_id IN (SELECT id FROM monitoring_runs WHERE business_id = $1)
`

func (q *Queries) TestQuery216(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery216, businessID)
	return err
}

const TestQuery217 = `-- name: TestQuery217 :exec
DELETE FROM monitoring_runs WHERE business_id = $1
`

func (q *Queries) TestQuery217(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery217, businessID)
	return err
}

const TestQuery218 = `-- name: TestQuery218 :exec
DELETE FROM profile_proposals WHERE business_id = $1
`

func (q *Queries) TestQuery218(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery218, businessID)
	return err
}

const TestQuery219 = `-- name: TestQuery219 :exec
DELETE FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery219(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery219, businessID)
	return err
}

const TestQuery220 = `-- name: TestQuery220 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery220(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery220, id)
	return err
}

const TestQuery221 = `-- name: TestQuery221 :exec
DELETE FROM subscriptions WHERE tenant_id = ANY($1)
`

func (q *Queries) TestQuery221(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery221, tenantID)
	return err
}

const TestQuery222 = `-- name: TestQuery222 :exec
DELETE FROM tenants WHERE id = ANY($1)
`

func (q *Queries) TestQuery222(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery222, id)
	return err
}

const TestQuery223 = `-- name: TestQuery223 :one
SELECT name FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery223(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, TestQuery223, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const TestQuery224 = `-- name: TestQuery224 :one
SELECT count(*) FROM prompts WHERE business_id = $1
`

func (q *Queries) TestQuery224(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery224, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery225 = `-- name: TestQuery225 :exec
INSERT INTO tenants (id, name) VALUES ($1, $2)
`

type TestQuery225Params struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) TestQuery225(ctx context.Context, arg TestQuery225Params) error {
	_, err := q.db.Exec(ctx, TestQuery225, arg.ID, arg.Name)
	return err
}

const TestQuery226 = `-- name: TestQuery226 :exec
INSERT INTO subscriptions (tenant_id, plan_code, comped) VALUES ($1, 'starter', true)
`

func (q *Queries) TestQuery226(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery226, tenantID)
	return err
}

const TestQuery227 = `-- name: TestQuery227 :exec
DELETE FROM prompt_results WHERE prompt_id = $1
`

func (q *Queries) TestQuery227(ctx context.Context, promptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery227, promptID)
	return err
}

const TestQuery228 = `-- name: TestQuery228 :exec
DELETE FROM monitoring_runs WHERE business_id = $1
`

func (q *Queries) TestQuery228(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery228, businessID)
	return err
}

const TestQuery229 = `-- name: TestQuery229 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery229(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery229, id)
	return err
}

const TestQuery230 = `-- name: TestQuery230 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery230(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery230, id)
	return err
}

const TestQuery231 = `-- name: TestQuery231 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery231(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery231, tenantID)
	return err
}

const TestQuery232 = `-- name: TestQuery232 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery232(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery232, id)
	return err
}

const TestQuery233 = `-- name: TestQuery233 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Activities Clinic', 'clinic', '{"country":"SG","city":"Singapore"}'::jsonb, now())
`

type TestQuery233Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery233(ctx context.Context, arg TestQuery233Params) error {
	_, err := q.db.Exec(ctx, TestQuery233, arg.ID, arg.TenantID)
	return err
}

const TestQuery234 = `-- name: TestQuery234 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic near me', 'active')
`

type TestQuery234Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery234(ctx context.Context, arg TestQuery234Params) error {
	_, err := q.db.Exec(ctx, TestQuery234, arg.ID, arg.BusinessID)
	return err
}

const TestQuery235 = `-- name: TestQuery235 :one
SELECT count(*) FROM monitoring_runs WHERE business_id = $1 AND scheduled_for = $2
`

type TestQuery235Params struct {
	BusinessID   uuid.UUID
	ScheduledFor time.Time
}

func (q *Queries) TestQuery235(ctx context.Context, arg TestQuery235Params) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery235, arg.BusinessID, arg.ScheduledFor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery236 = `-- name: TestQuery236 :exec
DELETE FROM citations WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery236(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery236, promptResultID)
	return err
}

const TestQuery237 = `-- name: TestQuery237 :exec
DELETE FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery237(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery237, promptResultID)
	return err
}

const TestQuery238 = `-- name: TestQuery238 :exec
DELETE FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery238(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery238, id)
	return err
}

const TestQuery239 = `-- name: TestQuery239 :exec
DELETE FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery239(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery239, id)
	return err
}

const TestQuery240 = `-- name: TestQuery240 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery240(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery240, id)
	return err
}

const TestQuery241 = `-- name: TestQuery241 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery241(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery241, id)
	return err
}

const TestQuery242 = `-- name: TestQuery242 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery242(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery242, tenantID)
	return err
}

const TestQuery243 = `-- name: TestQuery243 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery243(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery243, id)
	return err
}

const TestQuery244 = `-- name: TestQuery244 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Atlas Dental', 'clinic', '{"country":"SG","city":"Singapore"}'::jsonb, now())
`

type TestQuery244Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery244(ctx context.Context, arg TestQuery244Params) error {
	_, err := q.db.Exec(ctx, TestQuery244, arg.ID, arg.TenantID)
	return err
}

const TestQuery245 = `-- name: TestQuery245 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic for braces', 'active')
`

type TestQuery245Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery245(ctx context.Context, arg TestQuery245Params) error {
	_, err := q.db.Exec(ctx, TestQuery245, arg.ID, arg.BusinessID)
	return err
}

const TestQuery246 = `-- name: TestQuery246 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'analyze-wf', now())
`

type TestQuery246Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery246(ctx context.Context, arg TestQuery246Params) error {
	_, err := q.db.Exec(ctx, TestQuery246, arg.ID, arg.BusinessID)
	return err
}

const TestQuery247 = `-- name: TestQuery247 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5', '{"model":"gpt-5"}'::jsonb, $4::jsonb, $5)
`

type TestQuery247Params struct {
	ID           uuid.UUID
	RunID        uuid.UUID
	PromptID     uuid.UUID
	Column4      json.RawMessage
	ResponseText *string
}

func (q *Queries) TestQuery247(ctx context.Context, arg TestQuery247Params) error {
	_, err := q.db.Exec(ctx, TestQuery247,
		arg.ID,
		arg.RunID,
		arg.PromptID,
		arg.Column4,
		arg.ResponseText,
	)
	return err
}

const TestQuery248 = `-- name: TestQuery248 :one
SELECT sentiment, analysis_model, extraction_version FROM result_analyses WHERE prompt_result_id = $1
`

type TestQuery248Row struct {
	Sentiment         *string
	AnalysisModel     string
	ExtractionVersion int32
}

func (q *Queries) TestQuery248(ctx context.Context, promptResultID uuid.UUID) (TestQuery248Row, error) {
	row := q.db.QueryRow(ctx, TestQuery248, promptResultID)
	var i TestQuery248Row
	err := row.Scan(&i.Sentiment, &i.AnalysisModel, &i.ExtractionVersion)
	return i, err
}

const TestQuery249 = `-- name: TestQuery249 :one
SELECT url, domain, subject, cite_order FROM citations WHERE prompt_result_id = $1
`

type TestQuery249Row struct {
	Url       string
	Domain    string
	Subject   string
	CiteOrder int32
}

func (q *Queries) TestQuery249(ctx context.Context, promptResultID uuid.UUID) (TestQuery249Row, error) {
	row := q.db.QueryRow(ctx, TestQuery249, promptResultID)
	var i TestQuery249Row
	err := row.Scan(
		&i.Url,
		&i.Domain,
		&i.Subject,
		&i.CiteOrder,
	)
	return i, err
}

const TestQuery250 = `-- name: TestQuery250 :exec
DELETE FROM citations WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery250(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery250, promptResultID)
	return err
}

const TestQuery251 = `-- name: TestQuery251 :exec
DELETE FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery251(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery251, promptResultID)
	return err
}

const TestQuery252 = `-- name: TestQuery252 :one
SELECT count(*) FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery252(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery252, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery253 = `-- name: TestQuery253 :one
SELECT count(*) FROM result_analyses WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery253(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery253, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery254 = `-- name: TestQuery254 :one
SELECT count(*) FROM citations WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery254(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery254, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery255 = `-- name: TestQuery255 :exec
DELETE FROM profile_proposals WHERE business_id = $1
`

func (q *Queries) TestQuery255(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery255, businessID)
	return err
}

const TestQuery256 = `-- name: TestQuery256 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery256(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery256, id)
	return err
}

const TestQuery257 = `-- name: TestQuery257 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery257(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery257, tenantID)
	return err
}

const TestQuery258 = `-- name: TestQuery258 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery258(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery258, id)
	return err
}

const TestQuery259 = `-- name: TestQuery259 :exec
INSERT INTO businesses (id, tenant_id, status, name) VALUES ($1, $2, 'draft', 'Persist Clinic')
`

type TestQuery259Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery259(ctx context.Context, arg TestQuery259Params) error {
	_, err := q.db.Exec(ctx, TestQuery259, arg.ID, arg.TenantID)
	return err
}

const TestQuery260 = `-- name: TestQuery260 :exec
DELETE FROM mentions WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery260(ctx context.Context, promptResultID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery260, promptResultID)
	return err
}

const TestQuery261 = `-- name: TestQuery261 :exec
DELETE FROM competitors WHERE business_id = $1
`

func (q *Queries) TestQuery261(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery261, businessID)
	return err
}

const TestQuery262 = `-- name: TestQuery262 :exec
DELETE FROM prompt_results WHERE id = $1
`

func (q *Queries) TestQuery262(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery262, id)
	return err
}

const TestQuery263 = `-- name: TestQuery263 :exec
DELETE FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery263(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery263, id)
	return err
}

const TestQuery264 = `-- name: TestQuery264 :exec
DELETE FROM prompts WHERE id = $1
`

func (q *Queries) TestQuery264(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery264, id)
	return err
}

const TestQuery265 = `-- name: TestQuery265 :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) TestQuery265(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery265, id)
	return err
}

const TestQuery266 = `-- name: TestQuery266 :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) TestQuery266(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery266, tenantID)
	return err
}

const TestQuery267 = `-- name: TestQuery267 :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) TestQuery267(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery267, id)
	return err
}

const TestQuery268 = `-- name: TestQuery268 :exec
INSERT INTO businesses (id, tenant_id, status, name, category, location, activated_at)
VALUES ($1, $2, 'active', 'Atlas Dental', 'clinic', '{"country":"SG"}'::jsonb, now())
`

type TestQuery268Params struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) TestQuery268(ctx context.Context, arg TestQuery268Params) error {
	_, err := q.db.Exec(ctx, TestQuery268, arg.ID, arg.TenantID)
	return err
}

const TestQuery269 = `-- name: TestQuery269 :exec
INSERT INTO prompts (id, business_id, text, status) VALUES ($1, $2, 'best clinic', 'active')
`

type TestQuery269Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery269(ctx context.Context, arg TestQuery269Params) error {
	_, err := q.db.Exec(ctx, TestQuery269, arg.ID, arg.BusinessID)
	return err
}

const TestQuery270 = `-- name: TestQuery270 :exec
INSERT INTO monitoring_runs (id, business_id, platform, trigger, scheduled_for, status, workflow_id, completed_at)
VALUES ($1, $2, 'chatgpt', 'scheduled', '2026-07-13', 'completed', 'reconcile-wf', now())
`

type TestQuery270Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery270(ctx context.Context, arg TestQuery270Params) error {
	_, err := q.db.Exec(ctx, TestQuery270, arg.ID, arg.BusinessID)
	return err
}

const TestQuery271 = `-- name: TestQuery271 :exec
INSERT INTO prompt_results (id, run_id, prompt_id, status, model, request, raw_response, response_text)
VALUES ($1, $2, $3, 'succeeded', 'gpt-5', '{"model":"gpt-5"}'::jsonb, '{"id":"r"}'::jsonb, 'text')
`

type TestQuery271Params struct {
	ID       uuid.UUID
	RunID    uuid.UUID
	PromptID uuid.UUID
}

func (q *Queries) TestQuery271(ctx context.Context, arg TestQuery271Params) error {
	_, err := q.db.Exec(ctx, TestQuery271, arg.ID, arg.RunID, arg.PromptID)
	return err
}

const TestQuery272 = `-- name: TestQuery272 :exec
INSERT INTO competitors (id, business_id, name, aliases, source, status)
VALUES ($1, $2, 'Bravo Clinic', ARRAY['bravo clinic']::text[], 'manual', 'tracked')
`

type TestQuery272Params struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) TestQuery272(ctx context.Context, arg TestQuery272Params) error {
	_, err := q.db.Exec(ctx, TestQuery272, arg.ID, arg.BusinessID)
	return err
}

const TestQuery273 = `-- name: TestQuery273 :one
SELECT status, source FROM competitors WHERE business_id = $1 AND name = 'Charlie Medical'
`

type TestQuery273Row struct {
	Status string
	Source string
}

func (q *Queries) TestQuery273(ctx context.Context, businessID uuid.UUID) (TestQuery273Row, error) {
	row := q.db.QueryRow(ctx, TestQuery273, businessID)
	var i TestQuery273Row
	err := row.Scan(&i.Status, &i.Source)
	return i, err
}

const TestQuery274 = `-- name: TestQuery274 :one
SELECT to_jsonb(aliases) FROM competitors WHERE business_id = $1 AND name = 'Charlie Medical'
`

func (q *Queries) TestQuery274(ctx context.Context, businessID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, TestQuery274, businessID)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const TestQuery275 = `-- name: TestQuery275 :one
SELECT to_jsonb(suggested_aliases) FROM competitors WHERE id = $1
`

func (q *Queries) TestQuery275(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, TestQuery275, id)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const TestQuery276 = `-- name: TestQuery276 :one
SELECT to_jsonb(aliases) FROM competitors WHERE id = $1
`

func (q *Queries) TestQuery276(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, TestQuery276, id)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const TestQuery277 = `-- name: TestQuery277 :one
SELECT analysis_completed_at FROM monitoring_runs WHERE id = $1
`

func (q *Queries) TestQuery277(ctx context.Context, id uuid.UUID) (*time.Time, error) {
	row := q.db.QueryRow(ctx, TestQuery277, id)
	var analysis_completed_at *time.Time
	err := row.Scan(&analysis_completed_at)
	return analysis_completed_at, err
}

const TestQuery278 = `-- name: TestQuery278 :one
SELECT count(*) FROM competitors WHERE business_id = $1 AND name = 'Charlie Medical'
`

func (q *Queries) TestQuery278(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery278, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery279 = `-- name: TestQuery279 :one
SELECT count(*) FROM mentions WHERE prompt_result_id = $1
`

func (q *Queries) TestQuery279(ctx context.Context, promptResultID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery279, promptResultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery280 = `-- name: TestQuery280 :one
SELECT to_jsonb(suggested_aliases) FROM competitors WHERE id = $1
`

func (q *Queries) TestQuery280(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, TestQuery280, id)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const TestQuery281 = `-- name: TestQuery281 :one
SELECT matched_by, verbatim_name FROM mentions WHERE prompt_result_id = $1 AND subject = $2 AND mention_order = $3
`

type TestQuery281Params struct {
	PromptResultID uuid.UUID
	Subject        string
	MentionOrder   int32
}

type TestQuery281Row struct {
	MatchedBy    string
	VerbatimName *string
}

func (q *Queries) TestQuery281(ctx context.Context, arg TestQuery281Params) (TestQuery281Row, error) {
	row := q.db.QueryRow(ctx, TestQuery281, arg.PromptResultID, arg.Subject, arg.MentionOrder)
	var i TestQuery281Row
	err := row.Scan(&i.MatchedBy, &i.VerbatimName)
	return i, err
}

const TestQuery282 = `-- name: TestQuery282 :exec
INSERT INTO tenants (id, name) VALUES ($1, $2)
`

type TestQuery282Params struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) TestQuery282(ctx context.Context, arg TestQuery282Params) error {
	_, err := q.db.Exec(ctx, TestQuery282, arg.ID, arg.Name)
	return err
}

const TestQuery283 = `-- name: TestQuery283 :exec
INSERT INTO subscriptions (tenant_id, plan_code, comped) VALUES ($1, 'starter', true)
`

func (q *Queries) TestQuery283(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery283, tenantID)
	return err
}

const TestQuery284 = `-- name: TestQuery284 :one
SELECT count(*) FROM prompts WHERE business_id = $1 AND status = 'active'
`

func (q *Queries) TestQuery284(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, TestQuery284, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TestQuery285 = `-- name: TestQuery285 :one
SELECT status FROM profile_proposals WHERE id = $1
`

func (q *Queries) TestQuery285(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, TestQuery285, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const TestQuery286 = `-- name: TestQuery286 :exec
DELETE FROM mentions WHERE prompt_result_id IN (
  SELECT pr.id FROM prompt_results pr
  JOIN monitoring_runs r ON r.id = pr.run_id
  WHERE r.business_id = $1
)
`

func (q *Queries) TestQuery286(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery286, businessID)
	return err
}

const TestQuery287 = `-- name: TestQuery287 :exec
DELETE FROM citations WHERE prompt_result_id IN (
  SELECT pr.id FROM prompt_results pr
  JOIN monitoring_runs r ON r.id = pr.run_id
  WHERE r.business_id = $1
)
`

func (q *Queries) TestQuery287(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery287, businessID)
	return err
}

const TestQuery288 = `-- name: TestQuery288 :exec
DELETE FROM result_analyses WHERE prompt_result_id IN (
  SELECT pr.id FROM prompt_results pr
  JOIN monitoring_runs r ON r.id = pr.run_id
  WHERE r.business_id = $1
)
`

func (q *Queries) TestQuery288(ctx context.Context, businessID uuid.UUID) error {
	_, err := q.db.Exec(ctx, TestQuery288, businessID)
	return err
}
